Network node V2[5]
  <3,1000000>
  Template: DUDE[2]

  Template: DUDEX[2]

[1,1,5,2,2]
 i = 0 k = 0
 i = 1 k = 0
choices : first. 0	 second. 1
[1,1,5,2,2]
 i = 0 k = 1
choices : first. 0	 second. 1
( DEFINE ( DOMAIN MAZE )
( :REQUIREMENTS :CONDITIONAL-EFFECTS :TYPING )
( :TYPES
	AGENT - OBJECT
	LOCATION - OBJECT
	DOOR - OBJECT
	BRIDGE - OBJECT
	BOAT - OBJECT
	SWITCH - OBJECT
	AGENT-COUNT - OBJECT
)
( :CONSTANTS
	ACOUNT-0 - AGENT-COUNT
)
( :PREDICATES
	( AT ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( HAS-SWITCH ?SWITCH0 - SWITCH ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( BLOCKED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( HAS-DOOR ?DOOR0 - DOOR ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( HAS-BOAT ?BOAT0 - BOAT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( HAS-BRIDGE ?BRIDGE0 - BRIDGE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( AT ?BOAT0 - BOAT ?LOCATION1 - LOCATION )
	( AFREE )
	( ACTIVITY-FREE )
	( ATEMP )
	( TAKEN ?AGENT0 - AGENT )
	( CONSEC ?AGENT-COUNT0 - AGENT-COUNT ?AGENT-COUNT1 - AGENT-COUNT )
	( ACTIVE-V2 ?BOAT0 - BOAT )
	( COUNT-V2 ?AGENT-COUNT0 - AGENT-COUNT )
	( SAT-V2 ?AGENT-COUNT0 - AGENT-COUNT )
)
( :ACTION START-V2
  :PARAMETERS ( ?BOAT0 - BOAT )
  :PRECONDITION
	( AND
		( AFREE )
	)
  :EFFECT
	( AND
		( NOT ( AFREE ) )
		( ACTIVE-V2 ?BOAT0 )
		( COUNT-V2 ACOUNT-0 )
	)
)
( :ACTION DO-DUDE
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?BOAT2 - BOAT ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION ?AGENT-COUNT5 - AGENT-COUNT ?AGENT-COUNT6 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AT ?BOAT2 ?LOCATION3 )
		( ACTIVE-V2 ?BOAT2 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V2 ?AGENT-COUNT5 )
		( CONSEC ?AGENT-COUNT5 ?AGENT-COUNT6 )
	)
  :EFFECT
	( AND
		( AT ?BOAT2 ?LOCATION4 )
		( NOT ( AT ?BOAT2 ?LOCATION3 ) )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V2 ?AGENT-COUNT5 ) )
		( COUNT-V2 ?AGENT-COUNT6 )
	)
)
( :ACTION DO-DUDEX
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?BOAT2 - BOAT ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION ?AGENT-COUNT5 - AGENT-COUNT ?AGENT-COUNT6 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AT ?BOAT2 ?LOCATION3 )
		( ACTIVE-V2 ?BOAT2 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V2 ?AGENT-COUNT5 )
		( CONSEC ?AGENT-COUNT5 ?AGENT-COUNT6 )
	)
  :EFFECT
	( AND
		( AT ?BOAT2 ?LOCATION4 )
		( NOT ( AT ?BOAT2 ?LOCATION3 ) )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V2 ?AGENT-COUNT5 ) )
		( COUNT-V2 ?AGENT-COUNT6 )
	)
)
( :ACTION END-V2
  :PARAMETERS ( ?BOAT0 - BOAT ?AGENT-COUNT1 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( ACTIVITY-FREE )
		( COUNT-V2 ?AGENT-COUNT1 )
		( SAT-V2 ?AGENT-COUNT1 )
		( ACTIVE-V2 ?BOAT0 )
	)
  :EFFECT
	( AND
		( NOT ( COUNT-V2 ?AGENT-COUNT1 ) )
		( AFREE )
		( NOT ( ACTIVE-V2 ?BOAT0 ) )
		( FORALL
			( ?AGENT2 - AGENT )
			( NOT ( TAKEN ?AGENT2 ) )
		)
	)
)
( :ACTION FREE
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( ATEMP )
	)
  :EFFECT
	( AND
		( AFREE )
		( NOT ( ATEMP ) )
	)
)
)
