( DEFINE ( DOMAIN MAZE )
( :REQUIREMENTS :TYPING )
( :TYPES
	AGENT - OBJECT
	LOCATION - OBJECT
	DOOR - OBJECT
	BRIDGE - OBJECT
	BOAT - OBJECT
	SWITCH - OBJECT
	AGENT-COUNT - OBJECT
)
( :CONSTANTS
	ACOUNT-0 - AGENT-COUNT
)
( :PREDICATES
	( AT ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( HAS-SWITCH ?SWITCH0 - SWITCH ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( BLOCKED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( HAS-DOOR ?DOOR0 - DOOR ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( NEG-HAS-DOOR ?DOOR0 - DOOR ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( HAS-BOAT ?BOAT0 - BOAT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( HAS-BRIDGE ?BRIDGE0 - BRIDGE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( AFREE )
	( ACTIVITY-FREE )
	( ATEMP )
	( TAKEN ?AGENT0 - AGENT )
	( CONSEC ?AGENT-COUNT0 - AGENT-COUNT ?AGENT-COUNT1 - AGENT-COUNT )
	( CONSEC1 ?AGENT-COUNT0 - AGENT-COUNT ?AGENT-COUNT1 - AGENT-COUNT )
	( CONSEC1 ?AGENT0 - AGENT )
	( ACTIVE-V1 ?DOOR0 - DOOR )
	( COUNT-V1 ?AGENT-COUNT0 - AGENT-COUNT )
	( SAT-V1 ?AGENT-COUNT0 - AGENT-COUNT )
)
( :ACTION START-V1
  :PARAMETERS ( ?DOOR0 - DOOR )
  :PRECONDITION
	( AND
		( AFREE )
	)
  :EFFECT
	( AND
		( NOT ( AFREE ) )
		( ACTIVE-V1 ?DOOR0 )
		( COUNT-V1 ACOUNT-0 )
	)
)
( :ACTION DO-MOVE
  :PARAMETERS ( ?AGENT0 - AGENT ?DOOR1 - DOOR ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION ?AGENT-COUNT4 - AGENT-COUNT ?AGENT-COUNT5 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AT ?AGENT0 ?LOCATION2 )
		( NOT ( BLOCKED ?LOCATION2 ?LOCATION3 ) )
		( HAS-DOOR ?DOOR1 ?LOCATION2 ?LOCATION3 )
		( ACTIVE-V1 ?DOOR1 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V1 ?AGENT-COUNT4 )
		( CONSEC ?AGENT-COUNT4 ?AGENT-COUNT5 )
	)
  :EFFECT
	( AND
		( AT ?AGENT0 ?LOCATION3 )
		( NOT ( AT ?AGENT0 ?LOCATION2 ) )
		( NEG-HAS-DOOR ?DOOR1 ?LOCATION2 ?LOCATION3 )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V1 ?AGENT-COUNT4 ) )
		( COUNT-V1 ?AGENT-COUNT5 )
	)
)
( :ACTION END-V1
  :PARAMETERS ( ?DOOR0 - DOOR ?AGENT-COUNT1 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( ACTIVITY-FREE )
		( COUNT-V1 ?AGENT-COUNT1 )
		( SAT-V1 ?AGENT-COUNT1 )
		( ACTIVE-V1 ?DOOR0 )
	)
  :EFFECT
	( AND
		( NOT ( COUNT-V1 ?AGENT-COUNT1 ) )
		( ATEMP )
		( NOT ( ACTIVE-V1 ?DOOR0 ) )
		( FORALL
			( ?AGENT2 - AGENT )
			( NOT ( TAKEN ?AGENT2 ) )
		)
	)
)
( :ACTION DELETE-HAS-DOOR
  :PARAMETERS ( ?DOOR0 - DOOR ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( ATEMP )
		( NEG-HAS-DOOR ?DOOR0 ?LOCATION1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( HAS-DOOR ?DOOR0 ?LOCATION1 ?LOCATION2 ) )
		( NOT ( NEG-HAS-DOOR ?DOOR0 ?LOCATION1 ?LOCATION2 ) )
	)
)
( :ACTION POS-NEG-FREE
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( ATEMP )
		( FORALL
			( ?DOOR0 - DOOR ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
			( AND
				( NOT ( NEG-HAS-DOOR ?DOOR0 ?LOCATION1 ?LOCATION2 ) )
			)
		)
	)
  :EFFECT
	( AND
		( AFREE )
		( NOT ( ATEMP ) )
	)
)
)
