;;
;;	BOXPUSHING DOMAIN 
;;
( DEFINE ( DOMAIN BOXPUSHING )
( :REQUIREMENTS :TYPING )
( :TYPES
	AGENT - OBJECT
	BOX - OBJECT
	LOCATION - OBJECT
	AGENT-COUNT - OBJECT
)
( :CONSTANTS
	ACOUNT-0 - AGENT-COUNT
)
( :PREDICATES
	( BOX-AT-LOC ?BOX0 - BOX ?LOCATION1 - LOCATION )
	( POS-BOX-AT-LOC ?BOX0 - BOX ?LOCATION1 - LOCATION )
	( NEG-BOX-AT-LOC ?BOX0 - BOX ?LOCATION1 - LOCATION )
	( AGENT-AT-LOC ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( CONNECTED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( TIRED ?AGENT0 - AGENT )
	( TAKEN ?AGENT0 - AGENT )
	( CONSEC ?AGENT-COUNT0 - AGENT-COUNT ?AGENT-COUNT1 - AGENT-COUNT )
	( ACTIVE-V1 ?BOX0 - BOX ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( COUNT-V1 ?AGENT-COUNT0 - AGENT-COUNT )
	( SAT-V1 ?AGENT-COUNT0 - AGENT-COUNT )
	( ACTIVE-V2 ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( COUNT-V2 ?AGENT-COUNT0 - AGENT-COUNT )
	( SAT-V2 ?AGENT-COUNT0 - AGENT-COUNT )
	( AFREE )
	( IN-JOINT )
	( P-PUSH-BOX ?AGENT0 - AGENT ?BOX1 - BOX ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( NEXT-ACTIVITY-2-PUSH-BOX-2 ?BOX0 - BOX ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( P-ACTIVITY-2-PUSH-BOX ?AGENT0 - AGENT ?BOX1 - BOX ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( NEXT-ACTIVITY-3-PUSH-BOX-2 ?BOX0 - BOX ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( NEXT-ACTIVITY-3-PUSH-BOX-3 ?BOX0 - BOX ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( P-ACTIVITY-3-PUSH-BOX ?AGENT0 - AGENT ?BOX1 - BOX ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( NEXT-ACTIVITY-4-PUSH-BOX-2 ?BOX0 - BOX ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( NEXT-ACTIVITY-4-PUSH-BOX-3 ?BOX0 - BOX ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( NEXT-ACTIVITY-4-PUSH-BOX-4 ?BOX0 - BOX ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( P-ACTIVITY-4-PUSH-BOX ?AGENT0 - AGENT ?BOX1 - BOX ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( P-MOVE-AGENT ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
)
( :ACTION START-V1
  :PARAMETERS ( ?BOX0 - BOX ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( AFREE )
	)
  :EFFECT
	( AND
		( NOT ( AFREE ) )
		( ACTIVE-V1 ?BOX0 ?LOCATION1 ?LOCATION2 )
		( COUNT-V1 ACOUNT-0 )
	)
)
( :ACTION DO-PUSH-BOX
  :PARAMETERS ( ?AGENT0 - AGENT ?BOX1 - BOX ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION ?AGENT-COUNT4 - AGENT-COUNT ?AGENT-COUNT5 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION2 )
		( BOX-AT-LOC ?BOX1 ?LOCATION2 )
		( CONNECTED ?LOCATION2 ?LOCATION3 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( IN-JOINT ) )
		( ACTIVE-V1 ?BOX1 ?LOCATION2 ?LOCATION3 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V1 ?AGENT-COUNT4 )
		( CONSEC ?AGENT-COUNT4 ?AGENT-COUNT5 )
		( FORALL
			( ?AGENT6 - AGENT )
			( OR
				( NOT ( P-PUSH-BOX ?AGENT6 ?BOX1 ?LOCATION2 ?LOCATION3 ) )
			)
		)
		( FORALL
			( ?AGENT6 - AGENT ?AGENT7 - AGENT )
			( OR
				( NOT ( P-PUSH-BOX ?AGENT6 ?BOX1 ?LOCATION2 ?LOCATION3 ) )
				( NOT ( P-PUSH-BOX ?AGENT7 ?BOX1 ?LOCATION2 ?LOCATION3 ) )
			)
		)
		( FORALL
			( ?AGENT6 - AGENT ?AGENT7 - AGENT ?AGENT8 - AGENT )
			( OR
				( NOT ( P-PUSH-BOX ?AGENT6 ?BOX1 ?LOCATION2 ?LOCATION3 ) )
				( NOT ( P-PUSH-BOX ?AGENT7 ?BOX1 ?LOCATION2 ?LOCATION3 ) )
				( NOT ( P-PUSH-BOX ?AGENT8 ?BOX1 ?LOCATION2 ?LOCATION3 ) )
			)
		)
	)
  :EFFECT
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION3 )
		( POS-BOX-AT-LOC ?BOX1 ?LOCATION3 )
		( NOT ( AGENT-AT-LOC ?AGENT0 ?LOCATION2 ) )
		( NEG-BOX-AT-LOC ?BOX1 ?LOCATION2 )
		( TIRED ?AGENT0 )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V1 ?AGENT-COUNT4 ) )
		( COUNT-V1 ?AGENT-COUNT5 )
		( P-PUSH-BOX ?AGENT0 ?BOX1 ?LOCATION2 ?LOCATION3 )
	)
)
( :ACTION DO-ACTIVITY-2-PUSH-BOX-1
  :PARAMETERS ( ?AGENT0 - AGENT ?BOX2 - BOX ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION ?AGENT-COUNT5 - AGENT-COUNT ?AGENT-COUNT6 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION3 )
		( BOX-AT-LOC ?BOX2 ?LOCATION3 )
		( CONNECTED ?LOCATION3 ?LOCATION4 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( IN-JOINT ) )
		( ACTIVE-V1 ?BOX2 ?LOCATION3 ?LOCATION4 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V1 ?AGENT-COUNT5 )
		( CONSEC ?AGENT-COUNT5 ?AGENT-COUNT6 )
		( FORALL
			( ?AGENT7 - AGENT )
			( OR
				( NOT ( P-PUSH-BOX ?AGENT7 ?BOX2 ?LOCATION3 ?LOCATION4 ) )
			)
		)
		( FORALL
			( ?AGENT7 - AGENT ?AGENT8 - AGENT )
			( OR
				( NOT ( P-PUSH-BOX ?AGENT7 ?BOX2 ?LOCATION3 ?LOCATION4 ) )
				( NOT ( P-PUSH-BOX ?AGENT8 ?BOX2 ?LOCATION3 ?LOCATION4 ) )
			)
		)
	)
  :EFFECT
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION4 )
		( POS-BOX-AT-LOC ?BOX2 ?LOCATION4 )
		( NOT ( AGENT-AT-LOC ?AGENT0 ?LOCATION3 ) )
		( NEG-BOX-AT-LOC ?BOX2 ?LOCATION3 )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V1 ?AGENT-COUNT5 ) )
		( COUNT-V1 ?AGENT-COUNT6 )
		( IN-JOINT )
		( NEXT-ACTIVITY-2-PUSH-BOX-2 ?BOX2 ?LOCATION3 ?LOCATION4 )
		( P-ACTIVITY-2-PUSH-BOX ?AGENT0 ?BOX2 ?LOCATION3 ?LOCATION4 )
		( P-PUSH-BOX ?AGENT0 ?BOX2 ?LOCATION3 ?LOCATION4 )
	)
)
( :ACTION DO-ACTIVITY-2-PUSH-BOX-2
  :PARAMETERS ( ?AGENT0 - AGENT ?BOX2 - BOX ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION ?AGENT-COUNT5 - AGENT-COUNT ?AGENT-COUNT6 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION3 )
		( BOX-AT-LOC ?BOX2 ?LOCATION3 )
		( CONNECTED ?LOCATION3 ?LOCATION4 )
		( NOT ( TIRED ?AGENT0 ) )
		( NEXT-ACTIVITY-2-PUSH-BOX-2 ?BOX2 ?LOCATION3 ?LOCATION4 )
		( ACTIVE-V1 ?BOX2 ?LOCATION3 ?LOCATION4 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V1 ?AGENT-COUNT5 )
		( CONSEC ?AGENT-COUNT5 ?AGENT-COUNT6 )
	)
  :EFFECT
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION4 )
		( POS-BOX-AT-LOC ?BOX2 ?LOCATION4 )
		( NOT ( AGENT-AT-LOC ?AGENT0 ?LOCATION3 ) )
		( NEG-BOX-AT-LOC ?BOX2 ?LOCATION3 )
		( NOT ( IN-JOINT ) )
		( NOT ( NEXT-ACTIVITY-2-PUSH-BOX-2 ?BOX2 ?LOCATION3 ?LOCATION4 ) )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V1 ?AGENT-COUNT5 ) )
		( COUNT-V1 ?AGENT-COUNT6 )
		( P-PUSH-BOX ?AGENT0 ?BOX2 ?LOCATION3 ?LOCATION4 )
	)
)
( :ACTION DO-ACTIVITY-3-PUSH-BOX-1
  :PARAMETERS ( ?AGENT0 - AGENT ?BOX3 - BOX ?LOCATION4 - LOCATION ?LOCATION5 - LOCATION ?AGENT-COUNT6 - AGENT-COUNT ?AGENT-COUNT7 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION4 )
		( BOX-AT-LOC ?BOX3 ?LOCATION4 )
		( CONNECTED ?LOCATION4 ?LOCATION5 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( IN-JOINT ) )
		( ACTIVE-V1 ?BOX3 ?LOCATION4 ?LOCATION5 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V1 ?AGENT-COUNT6 )
		( CONSEC ?AGENT-COUNT6 ?AGENT-COUNT7 )
		( FORALL
			( ?AGENT8 - AGENT )
			( OR
				( NOT ( P-PUSH-BOX ?AGENT8 ?BOX3 ?LOCATION4 ?LOCATION5 ) )
			)
		)
	)
  :EFFECT
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION5 )
		( POS-BOX-AT-LOC ?BOX3 ?LOCATION5 )
		( NOT ( AGENT-AT-LOC ?AGENT0 ?LOCATION4 ) )
		( NEG-BOX-AT-LOC ?BOX3 ?LOCATION4 )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V1 ?AGENT-COUNT6 ) )
		( COUNT-V1 ?AGENT-COUNT7 )
		( IN-JOINT )
		( NEXT-ACTIVITY-3-PUSH-BOX-2 ?BOX3 ?LOCATION4 ?LOCATION5 )
		( P-ACTIVITY-3-PUSH-BOX ?AGENT0 ?BOX3 ?LOCATION4 ?LOCATION5 )
		( P-PUSH-BOX ?AGENT0 ?BOX3 ?LOCATION4 ?LOCATION5 )
	)
)
( :ACTION DO-ACTIVITY-3-PUSH-BOX-2
  :PARAMETERS ( ?AGENT0 - AGENT ?BOX3 - BOX ?LOCATION4 - LOCATION ?LOCATION5 - LOCATION ?AGENT-COUNT6 - AGENT-COUNT ?AGENT-COUNT7 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION4 )
		( BOX-AT-LOC ?BOX3 ?LOCATION4 )
		( CONNECTED ?LOCATION4 ?LOCATION5 )
		( NOT ( TIRED ?AGENT0 ) )
		( ACTIVE-V1 ?BOX3 ?LOCATION4 ?LOCATION5 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V1 ?AGENT-COUNT6 )
		( CONSEC ?AGENT-COUNT6 ?AGENT-COUNT7 )
		( NEXT-ACTIVITY-3-PUSH-BOX-2 ?BOX3 ?LOCATION4 ?LOCATION5 )
	)
  :EFFECT
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION5 )
		( POS-BOX-AT-LOC ?BOX3 ?LOCATION5 )
		( NOT ( AGENT-AT-LOC ?AGENT0 ?LOCATION4 ) )
		( NEG-BOX-AT-LOC ?BOX3 ?LOCATION4 )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V1 ?AGENT-COUNT6 ) )
		( COUNT-V1 ?AGENT-COUNT7 )
		( NOT ( NEXT-ACTIVITY-3-PUSH-BOX-2 ?BOX3 ?LOCATION4 ?LOCATION5 ) )
		( NEXT-ACTIVITY-3-PUSH-BOX-3 ?BOX3 ?LOCATION4 ?LOCATION5 )
		( P-PUSH-BOX ?AGENT0 ?BOX3 ?LOCATION4 ?LOCATION5 )
	)
)
( :ACTION DO-ACTIVITY-3-PUSH-BOX-3
  :PARAMETERS ( ?AGENT0 - AGENT ?BOX3 - BOX ?LOCATION4 - LOCATION ?LOCATION5 - LOCATION ?AGENT-COUNT6 - AGENT-COUNT ?AGENT-COUNT7 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION4 )
		( BOX-AT-LOC ?BOX3 ?LOCATION4 )
		( CONNECTED ?LOCATION4 ?LOCATION5 )
		( NOT ( TIRED ?AGENT0 ) )
		( NEXT-ACTIVITY-3-PUSH-BOX-3 ?BOX3 ?LOCATION4 ?LOCATION5 )
		( ACTIVE-V1 ?BOX3 ?LOCATION4 ?LOCATION5 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V1 ?AGENT-COUNT6 )
		( CONSEC ?AGENT-COUNT6 ?AGENT-COUNT7 )
	)
  :EFFECT
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION5 )
		( POS-BOX-AT-LOC ?BOX3 ?LOCATION5 )
		( NOT ( AGENT-AT-LOC ?AGENT0 ?LOCATION4 ) )
		( NEG-BOX-AT-LOC ?BOX3 ?LOCATION4 )
		( NOT ( IN-JOINT ) )
		( NOT ( NEXT-ACTIVITY-3-PUSH-BOX-3 ?BOX3 ?LOCATION4 ?LOCATION5 ) )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V1 ?AGENT-COUNT6 ) )
		( COUNT-V1 ?AGENT-COUNT7 )
		( P-PUSH-BOX ?AGENT0 ?BOX3 ?LOCATION4 ?LOCATION5 )
	)
)
( :ACTION DO-ACTIVITY-4-PUSH-BOX-1
  :PARAMETERS ( ?AGENT0 - AGENT ?BOX4 - BOX ?LOCATION5 - LOCATION ?LOCATION6 - LOCATION ?AGENT-COUNT7 - AGENT-COUNT ?AGENT-COUNT8 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION5 )
		( BOX-AT-LOC ?BOX4 ?LOCATION5 )
		( CONNECTED ?LOCATION5 ?LOCATION6 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( IN-JOINT ) )
		( ACTIVE-V1 ?BOX4 ?LOCATION5 ?LOCATION6 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V1 ?AGENT-COUNT7 )
		( CONSEC ?AGENT-COUNT7 ?AGENT-COUNT8 )
	)
  :EFFECT
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION6 )
		( POS-BOX-AT-LOC ?BOX4 ?LOCATION6 )
		( NOT ( AGENT-AT-LOC ?AGENT0 ?LOCATION5 ) )
		( NEG-BOX-AT-LOC ?BOX4 ?LOCATION5 )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V1 ?AGENT-COUNT7 ) )
		( COUNT-V1 ?AGENT-COUNT8 )
		( IN-JOINT )
		( NEXT-ACTIVITY-4-PUSH-BOX-2 ?BOX4 ?LOCATION5 ?LOCATION6 )
		( P-ACTIVITY-4-PUSH-BOX ?AGENT0 ?BOX4 ?LOCATION5 ?LOCATION6 )
		( P-PUSH-BOX ?AGENT0 ?BOX4 ?LOCATION5 ?LOCATION6 )
	)
)
( :ACTION DO-ACTIVITY-4-PUSH-BOX-2
  :PARAMETERS ( ?AGENT0 - AGENT ?BOX4 - BOX ?LOCATION5 - LOCATION ?LOCATION6 - LOCATION ?AGENT-COUNT7 - AGENT-COUNT ?AGENT-COUNT8 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION5 )
		( BOX-AT-LOC ?BOX4 ?LOCATION5 )
		( CONNECTED ?LOCATION5 ?LOCATION6 )
		( NOT ( TIRED ?AGENT0 ) )
		( ACTIVE-V1 ?BOX4 ?LOCATION5 ?LOCATION6 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V1 ?AGENT-COUNT7 )
		( CONSEC ?AGENT-COUNT7 ?AGENT-COUNT8 )
		( NEXT-ACTIVITY-4-PUSH-BOX-2 ?BOX4 ?LOCATION5 ?LOCATION6 )
	)
  :EFFECT
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION6 )
		( POS-BOX-AT-LOC ?BOX4 ?LOCATION6 )
		( NOT ( AGENT-AT-LOC ?AGENT0 ?LOCATION5 ) )
		( NEG-BOX-AT-LOC ?BOX4 ?LOCATION5 )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V1 ?AGENT-COUNT7 ) )
		( COUNT-V1 ?AGENT-COUNT8 )
		( NOT ( NEXT-ACTIVITY-4-PUSH-BOX-2 ?BOX4 ?LOCATION5 ?LOCATION6 ) )
		( NEXT-ACTIVITY-4-PUSH-BOX-3 ?BOX4 ?LOCATION5 ?LOCATION6 )
		( P-PUSH-BOX ?AGENT0 ?BOX4 ?LOCATION5 ?LOCATION6 )
	)
)
( :ACTION DO-ACTIVITY-4-PUSH-BOX-3
  :PARAMETERS ( ?AGENT0 - AGENT ?BOX4 - BOX ?LOCATION5 - LOCATION ?LOCATION6 - LOCATION ?AGENT-COUNT7 - AGENT-COUNT ?AGENT-COUNT8 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION5 )
		( BOX-AT-LOC ?BOX4 ?LOCATION5 )
		( CONNECTED ?LOCATION5 ?LOCATION6 )
		( NOT ( TIRED ?AGENT0 ) )
		( ACTIVE-V1 ?BOX4 ?LOCATION5 ?LOCATION6 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V1 ?AGENT-COUNT7 )
		( CONSEC ?AGENT-COUNT7 ?AGENT-COUNT8 )
		( NEXT-ACTIVITY-4-PUSH-BOX-3 ?BOX4 ?LOCATION5 ?LOCATION6 )
	)
  :EFFECT
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION6 )
		( POS-BOX-AT-LOC ?BOX4 ?LOCATION6 )
		( NOT ( AGENT-AT-LOC ?AGENT0 ?LOCATION5 ) )
		( NEG-BOX-AT-LOC ?BOX4 ?LOCATION5 )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V1 ?AGENT-COUNT7 ) )
		( COUNT-V1 ?AGENT-COUNT8 )
		( NOT ( NEXT-ACTIVITY-4-PUSH-BOX-3 ?BOX4 ?LOCATION5 ?LOCATION6 ) )
		( NEXT-ACTIVITY-4-PUSH-BOX-4 ?BOX4 ?LOCATION5 ?LOCATION6 )
		( P-PUSH-BOX ?AGENT0 ?BOX4 ?LOCATION5 ?LOCATION6 )
	)
)
( :ACTION DO-ACTIVITY-4-PUSH-BOX-4
  :PARAMETERS ( ?AGENT0 - AGENT ?BOX4 - BOX ?LOCATION5 - LOCATION ?LOCATION6 - LOCATION ?AGENT-COUNT7 - AGENT-COUNT ?AGENT-COUNT8 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION5 )
		( BOX-AT-LOC ?BOX4 ?LOCATION5 )
		( CONNECTED ?LOCATION5 ?LOCATION6 )
		( NOT ( TIRED ?AGENT0 ) )
		( NEXT-ACTIVITY-4-PUSH-BOX-4 ?BOX4 ?LOCATION5 ?LOCATION6 )
		( ACTIVE-V1 ?BOX4 ?LOCATION5 ?LOCATION6 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V1 ?AGENT-COUNT7 )
		( CONSEC ?AGENT-COUNT7 ?AGENT-COUNT8 )
	)
  :EFFECT
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION6 )
		( POS-BOX-AT-LOC ?BOX4 ?LOCATION6 )
		( NOT ( AGENT-AT-LOC ?AGENT0 ?LOCATION5 ) )
		( NEG-BOX-AT-LOC ?BOX4 ?LOCATION5 )
		( NOT ( IN-JOINT ) )
		( NOT ( NEXT-ACTIVITY-4-PUSH-BOX-4 ?BOX4 ?LOCATION5 ?LOCATION6 ) )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V1 ?AGENT-COUNT7 ) )
		( COUNT-V1 ?AGENT-COUNT8 )
		( P-PUSH-BOX ?AGENT0 ?BOX4 ?LOCATION5 ?LOCATION6 )
	)
)
( :ACTION END-V1
  :PARAMETERS ( ?BOX0 - BOX ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?AGENT-COUNT3 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( NOT ( IN-JOINT ) )
		( COUNT-V1 ?AGENT-COUNT3 )
		( SAT-V1 ?AGENT-COUNT3 )
		( ACTIVE-V1 ?BOX0 ?LOCATION1 ?LOCATION2 )
	)
  :EFFECT
	( AND
		( NOT ( COUNT-V1 ?AGENT-COUNT3 ) )
		( AFREE )
		( NOT ( ACTIVE-V1 ?BOX0 ?LOCATION1 ?LOCATION2 ) )
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( P-PUSH-BOX ?AGENT4 ?BOX0 ?LOCATION1 ?LOCATION2 ) )
		)
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( P-ACTIVITY-2-PUSH-BOX ?AGENT4 ?BOX0 ?LOCATION1 ?LOCATION2 ) )
		)
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( P-ACTIVITY-3-PUSH-BOX ?AGENT4 ?BOX0 ?LOCATION1 ?LOCATION2 ) )
		)
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( P-ACTIVITY-4-PUSH-BOX ?AGENT4 ?BOX0 ?LOCATION1 ?LOCATION2 ) )
		)
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( TAKEN ?AGENT4 ) )
		)
		( FORALL
			( ?LOCATION4 - LOCATION )
			( AND
				( WHEN
					( POS-BOX-AT-LOC ?BOX0 ?LOCATION4 )
					( AND
						( BOX-AT-LOC ?BOX0 ?LOCATION4 )
						( NOT ( POS-BOX-AT-LOC ?BOX0 ?LOCATION4 ) )
					)
				)
				( WHEN
					( NEG-BOX-AT-LOC ?BOX0 ?LOCATION4 )
					( AND
						( NOT ( BOX-AT-LOC ?BOX0 ?LOCATION4 ) )
						( NOT ( NEG-BOX-AT-LOC ?BOX0 ?LOCATION4 ) )
					)
				)
			)
		)
	)
)
( :ACTION START-V2
  :PARAMETERS ( ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
  :PRECONDITION
	( AND
		( AFREE )
	)
  :EFFECT
	( AND
		( NOT ( AFREE ) )
		( ACTIVE-V2 ?LOCATION0 ?LOCATION1 )
		( COUNT-V2 ACOUNT-0 )
	)
)
( :ACTION DO-MOVE-AGENT
  :PARAMETERS ( ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?AGENT-COUNT3 - AGENT-COUNT ?AGENT-COUNT4 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION1 )
		( CONNECTED ?LOCATION1 ?LOCATION2 )
		( NOT ( IN-JOINT ) )
		( ACTIVE-V2 ?LOCATION1 ?LOCATION2 )
		( NOT ( TAKEN ?AGENT0 ) )
		( COUNT-V2 ?AGENT-COUNT3 )
		( CONSEC ?AGENT-COUNT3 ?AGENT-COUNT4 )
	)
  :EFFECT
	( AND
		( NOT ( AGENT-AT-LOC ?AGENT0 ?LOCATION1 ) )
		( AGENT-AT-LOC ?AGENT0 ?LOCATION2 )
		( TAKEN ?AGENT0 )
		( NOT ( COUNT-V2 ?AGENT-COUNT3 ) )
		( COUNT-V2 ?AGENT-COUNT4 )
		( P-MOVE-AGENT ?AGENT0 ?LOCATION1 ?LOCATION2 )
	)
)
( :ACTION END-V2
  :PARAMETERS ( ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION ?AGENT-COUNT2 - AGENT-COUNT )
  :PRECONDITION
	( AND
		( NOT ( IN-JOINT ) )
		( COUNT-V2 ?AGENT-COUNT2 )
		( SAT-V2 ?AGENT-COUNT2 )
		( ACTIVE-V2 ?LOCATION0 ?LOCATION1 )
	)
  :EFFECT
	( AND
		( NOT ( COUNT-V2 ?AGENT-COUNT2 ) )
		( AFREE )
		( NOT ( ACTIVE-V2 ?LOCATION0 ?LOCATION1 ) )
		( FORALL
			( ?AGENT3 - AGENT )
			( NOT ( P-MOVE-AGENT ?AGENT3 ?LOCATION0 ?LOCATION1 ) )
		)
		( FORALL
			( ?AGENT3 - AGENT )
			( NOT ( TAKEN ?AGENT3 ) )
		)
	)
)
)

;Domain compilation time is: 0.003101

