( DEFINE ( PROBLEM MAZE5_4_1 )
( :DOMAIN MAZE )
( :OBJECTS
	A1 A2 - AGENT
	LOC4X2 LOC3X2 - LOCATION
	B3 - BRIDGE
	ACOUNT-1 ACOUNT-2 - AGENT-COUNT
)
( :INIT
	( AT A1 LOC4X2 )
	( AT A2 LOC4X2 )
	( HAS-BRIDGE B3 LOC3X2 LOC4X2 )
	( HAS-BRIDGE B3 LOC4X2 LOC3X2 )
	( AFREE )
	( CONSEC ACOUNT-0 ACOUNT-1 )
	( CONSEC ACOUNT-1 ACOUNT-2 )
	( SAT-V1 ACOUNT-1 )
	( SAT-V1 ACOUNT-2 )
)
( :GOAL
	( AND
		( AT A1 LOC3X2 )
		( AFREE )
	)
)
)
