( DEFINE ( PROBLEM APARTMENTMOVERS1_1 )
( :DOMAIN APARTMENTMOVERS )
( :OBJECTS
	TABLE1 - TABLE
	SOFA1 - SOFA
	BED1 - BED
	CARTON1 CARTON2 - CARTON
	FR1 - FRIDGE
	TV1 - TELEVISION
	TR1 - TRUCK
	CAR1 CAR2 - CAR
	A1 A2 A3 - AGENT
	LOC1 LOC2 - LOCATION
	ACOUNT-1 ACOUNT-2 ACOUNT-3 - AGENT-COUNT
)
( :INIT
	( AT A1 LOC1 )
	( AT A2 LOC1 )
	( AT A3 LOC1 )
	( AT CAR1 LOC1 )
	( AT CAR2 LOC2 )
	( AT TR1 LOC1 )
	( AT TABLE1 LOC1 )
	( AT SOFA1 LOC1 )
	( AT BED1 LOC1 )
	( AT FR1 LOC1 )
	( AT TV1 LOC1 )
	( AT CARTON1 LOC1 )
	( AT CARTON2 LOC1 )
	( CONNECTED LOC1 LOC2 )
	( CONNECTED LOC2 LOC1 )
	( AFREE )
	( CONSEC ACOUNT-0 ACOUNT-1 )
	( CONSEC ACOUNT-1 ACOUNT-2 )
	( CONSEC ACOUNT-2 ACOUNT-3 )
	( SAT-V1 ACOUNT-1 )
	( SAT-V1 ACOUNT-2 )
	( SAT-V1 ACOUNT-3 )
	( SAT-V2 ACOUNT-1 )
	( SAT-V2 ACOUNT-2 )
	( SAT-V3 ACOUNT-1 )
	( SAT-V3 ACOUNT-2 )
	( SAT-V4 ACOUNT-2 )
	( SAT-V5 ACOUNT-1 )
	( SAT-V5 ACOUNT-2 )
	( SAT-V5 ACOUNT-3 )
	( SAT-V6 ACOUNT-2 )
)
( :GOAL
	( AND
		( AT TABLE1 LOC2 )
		( AFREE )
	)
)
)
