( DEFINE ( PROBLEM MAZE5_4_1 )
( :DOMAIN MAZE )
( :OBJECTS
	A1 A2 - AGENT
	:PRIVATE LOC4X2 LOC3X2 - LOCATION
	B3 - BRIDGE
	ACOUNT-1 ACOUNT-2 ACOUNT-3 ACOUNT-4 - AGENT-COUNT
	( :PRIVATE
		SS1 SS - AGENT
		DUMMY DRIVER7 - LOCATION
	)
)
( :INIT
	( AT A1 LOC4X2 )
	( AT A2 LOC4X2 )
	( HAS-BRIDGE B3 LOC3X2 LOC4X2 )
	( HAS-BRIDGE B3 LOC4X2 LOC3X2 )
	( AFREE )
	( CONSEC ACOUNT-0 ACOUNT-1 )
	( CONSEC ACOUNT-1 ACOUNT-2 )
	( CONSEC ACOUNT-2 ACOUNT-3 )
	( CONSEC ACOUNT-3 ACOUNT-4 )
	( SAT-V2 ACOUNT-1 )
	( SAT-V2 ACOUNT-2 )
)
( :GOAL
	( AND
		( AT A1 LOC3X2 )
		( AFREE )
	)
)
)
