( DEFINE ( PROBLEM PUSH-BOX-1_1 )
( :DOMAIN BOXPUSHING )
( :OBJECTS
	A1 A2 A3 - AGENT
	BOX1 BOX2 - BOX
	LOC1 LOC2 LOC3 - LOCATION
	ACOUNT-1 ACOUNT-2 ACOUNT-3 ACOUNT-4 - AGENT-COUNT
)
( :INIT
	( AGENT-AT-LOC A1 LOC2 )
	( AGENT-AT-LOC A2 LOC2 )
	( AGENT-AT-LOC A3 LOC2 )
	( BOX-AT-LOC BOX1 LOC1 )
	( BOX-AT-LOC BOX2 LOC1 )
	( CONNECTED LOC1 LOC2 )
	( CONNECTED LOC2 LOC1 )
	( CONNECTED LOC3 LOC2 )
	( CONNECTED LOC2 LOC3 )
	( AFREE )
	( CONSEC ACOUNT-0 ACOUNT-1 )
	( CONSEC ACOUNT-1 ACOUNT-2 )
	( CONSEC ACOUNT-2 ACOUNT-3 )
	( CONSEC ACOUNT-3 ACOUNT-4 )
	( SAT-V2 ACOUNT-2 )
	( SAT-V1 ACOUNT-1 )
	( SAT-V1 ACOUNT-2 )
	( SAT-V1 ACOUNT-3 )
	( SAT-V1 ACOUNT-4 )
)
( :GOAL
	( AND
		( BOX-AT-LOC BOX1 LOC3 )
		( BOX-AT-LOC BOX2 LOC3 )
		( AFREE )
	)
)
)
