( DEFINE ( PROBLEM PUSH-BOX-1_1 )
( :DOMAIN BOXPUSHING )
( :OBJECTS
	A2 - AGENT
	BOX - BOX
	LOC1 LOC2 - LOCATION
	ACOUNT-1 - AGENT-COUNT
)
( :INIT
	( BOX-AT-LOC BOX LOC1 )
	( AGENT-AT-LOC A2 LOC1 )
	( CONNECTED LOC1 LOC2 )
	( AFREE )
	( CONSEC ACOUNT-0 ACOUNT-1 )
	( SAT-V2 ACOUNT-1 )
)
( :GOAL
	( AND
		( BOX-AT-LOC BOX LOC2 )
		( AFREE )
	)
)
)
