;;
;;	BOXPUSHING DOMAIN 
;;
( DEFINE ( DOMAIN BOXPUSHING )
( :REQUIREMENTS :TYPING )
( :TYPES
	OBJECT - OBJECT
	AGENT - OBJECT
	BOX - OBJECT
	LOCATION - OBJECT
)
( :PREDICATES
	( BOX-AT-LOC ?BOX0 - BOX ?LOCATION1 - LOCATION )
	( POS-BOX-AT-LOC ?BOX0 - BOX ?LOCATION1 - LOCATION )
	( NEG-BOX-AT-LOC ?BOX0 - BOX ?LOCATION1 - LOCATION )
	( AGENT-AT-LOC ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( POS-AGENT-AT-LOC ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( NEG-AGENT-AT-LOC ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( CONNECTED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( POS-CONNECTED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( NEG-CONNECTED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( TIRED ?AGENT0 - AGENT )
	( POS-TIRED ?AGENT0 - AGENT )
	( NEG-TIRED ?AGENT0 - AGENT )
	( SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( POS-SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( NEG-SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( INTACT ?BOX0 - BOX )
	( POS-INTACT ?BOX0 - BOX )
	( NEG-INTACT ?BOX0 - BOX )
	( TAKEN ?AGENT0 - AGENT )
	( NEG-IN-JOINT )
	( P-MOVE-AGENT ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( P-PUSH-BOX ?AGENT0 - AGENT ?BOX1 - BOX ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( P-2-PUSH-BOX ?AGENT0 - AGENT ?AGENT1 - AGENT ?BOX2 - BOX ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION )
	( P-3-PUSH-BOX ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?BOX3 - BOX ?LOCATION4 - LOCATION ?LOCATION5 - LOCATION )
	( P-4-PUSH-BOX ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?AGENT3 - AGENT ?BOX4 - BOX ?LOCATION5 - LOCATION ?LOCATION6 - LOCATION )
	( PPP ?BOX1 - BOX ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION ) 
)
( :ACTION MULTI-START
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( NEG-IN-JOINT )
	)
  :EFFECT
	( AND
		( NOT ( NEG-IN-JOINT ) )
	)
)
( :ACTION MOVE-AGENT
  :PARAMETERS ( ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION1 )
		( CONNECTED ?LOCATION1 ?LOCATION2 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( NEG-AGENT-AT-LOC ?AGENT0 ?LOCATION1 )
		( POS-AGENT-AT-LOC ?AGENT0 ?LOCATION2 )
		( TAKEN ?AGENT0 )
		( P-MOVE-AGENT ?AGENT0 ?LOCATION1 ?LOCATION2 )
	)
)
( :ACTION PUSH-BOX
  :PARAMETERS ( ?AGENT0 - AGENT ?BOX1 - BOX ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION2 )
		( BOX-AT-LOC ?BOX1 ?LOCATION2 )
		( CONNECTED ?LOCATION2 ?LOCATION3 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
		( PPP ?BOX1 ?LOCATION2 ?LOCATION3 )
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( P-PUSH-BOX ?AGENT4 ?BOX1 ?LOCATION2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT5 - AGENT ?LOCATION6 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION3 ?LOCATION6 ) )
					( P-PUSH-BOX ?AGENT5 ?BOX1 ?LOCATION2 ?LOCATION6 ) 
				)
			) 
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?LOCATION7 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION3 ?LOCATION7 ) )
					( P-2-PUSH-BOX ?AGENT5 ?AGENT6 ?BOX1 ?LOCATION2 ?LOCATION7 ) 
				) 
			)
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?AGENT7 - AGENT ?LOCATION8 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION3 ?LOCATION8 ) )
					( P-3-PUSH-BOX ?AGENT5 ?AGENT6 ?AGENT7 ?BOX1 ?LOCATION2 ?LOCATION8 ) 
				)
			)
		)
		( FORALL
			( ?AGENT7 - AGENT ?AGENT8 - AGENT ?AGENT9 - AGENT ?AGENT10 - AGENT ?LOCATION11 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION3 ?LOCATION11 ) )
					( P-4-PUSH-BOX ?AGENT7 ?AGENT8 ?AGENT9 ?AGENT10 ?BOX1 ?LOCATION2 ?LOCATION11 ) 
				)
			)
		)
	)
  :EFFECT
	( AND
		( POS-AGENT-AT-LOC ?AGENT0 ?LOCATION3 )
		( POS-BOX-AT-LOC ?BOX1 ?LOCATION3 )
		( NEG-AGENT-AT-LOC ?AGENT0 ?LOCATION2 )
		( NEG-BOX-AT-LOC ?BOX1 ?LOCATION2 )
		( POS-TIRED ?AGENT0 )
		( TAKEN ?AGENT0 )
		( P-PUSH-BOX ?AGENT0 ?BOX1 ?LOCATION2 ?LOCATION3 )
	)
)
( :ACTION 2-PUSH-BOX
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?BOX2 - BOX ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION3 )
		( AGENT-AT-LOC ?AGENT1 ?LOCATION3 )
		( BOX-AT-LOC ?BOX2 ?LOCATION3 )
		( CONNECTED ?LOCATION3 ?LOCATION4 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TIRED ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT5 - AGENT )
			( NOT ( P-PUSH-BOX ?AGENT5 ?BOX2 ?LOCATION3 ?LOCATION4 ) )
		)
		( FORALL
			( ?AGENT5 - AGENT ?LOCATION6 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION4 ?LOCATION6 ) )
					( P-PUSH-BOX ?AGENT5 ?BOX2 ?LOCATION3 ?LOCATION6 ) 
				)
			)
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?LOCATION7 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION4 ?LOCATION7 ) )
					( P-2-PUSH-BOX ?AGENT5 ?AGENT6 ?BOX2 ?LOCATION3 ?LOCATION7 ) 
				) 
			)
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?AGENT7 - AGENT ?LOCATION8 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION4 ?LOCATION8 ) )
					( P-3-PUSH-BOX ?AGENT5 ?AGENT6 ?AGENT7 ?BOX2 ?LOCATION3 ?LOCATION8 ) 
				) 
			)
		)
		( FORALL
			( ?AGENT7 - AGENT ?AGENT8 - AGENT ?AGENT9 - AGENT ?AGENT10 - AGENT ?LOCATION11 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION4 ?LOCATION11 ) )
					( P-4-PUSH-BOX ?AGENT7 ?AGENT8 ?AGENT9 ?AGENT10 ?BOX2 ?LOCATION3 ?LOCATION11 ) 
				)
			)
		)
	)
  :EFFECT
	( AND
		( POS-AGENT-AT-LOC ?AGENT0 ?LOCATION4 )
		( POS-AGENT-AT-LOC ?AGENT1 ?LOCATION4 )
		( POS-BOX-AT-LOC ?BOX2 ?LOCATION4 )
		( NEG-AGENT-AT-LOC ?AGENT0 ?LOCATION3 )
		( NEG-AGENT-AT-LOC ?AGENT1 ?LOCATION3 )
		( NEG-BOX-AT-LOC ?BOX2 ?LOCATION3 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( PPP ?BOX2 ?LOCATION3 ?LOCATION4 )
		( P-2-PUSH-BOX ?AGENT0 ?AGENT1 ?BOX2 ?LOCATION3 ?LOCATION4 )
		( P-PUSH-BOX ?AGENT0 ?BOX2 ?LOCATION3 ?LOCATION4 )
		( P-PUSH-BOX ?AGENT1 ?BOX2 ?LOCATION3 ?LOCATION4 )
	)
)
( :ACTION 3-PUSH-BOX
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?BOX3 - BOX ?LOCATION4 - LOCATION ?LOCATION5 - LOCATION )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION4 )
		( AGENT-AT-LOC ?AGENT1 ?LOCATION4 )
		( AGENT-AT-LOC ?AGENT2 ?LOCATION4 )
		( BOX-AT-LOC ?BOX3 ?LOCATION4 )
		( CONNECTED ?LOCATION4 ?LOCATION5 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TIRED ?AGENT1 ) )
		( NOT ( TIRED ?AGENT2 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT2 ) )
		( NOT ( SAME-AGENT ?AGENT2 ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT2 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT6 - AGENT )
			( NOT ( P-PUSH-BOX ?AGENT6 ?BOX3 ?LOCATION4 ?LOCATION5 ) )
		)
		( FORALL
			( ?AGENT5 - AGENT ?LOCATION6 - LOCATION )
			( OR ( NOT ( = ?LOCATION5 ?LOCATION6 ) )
				( NOT ( P-PUSH-BOX ?AGENT5 ?BOX3 ?LOCATION4 ?LOCATION6 ) ) 
			)
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?LOCATION7 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION5 ?LOCATION7 ) )
					( P-2-PUSH-BOX ?AGENT5 ?AGENT6 ?BOX3 ?LOCATION4 ?LOCATION7 ) 
				) 
			)
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?AGENT7 - AGENT ?LOCATION8 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION5 ?LOCATION8 ) )
					( P-3-PUSH-BOX ?AGENT5 ?AGENT6 ?AGENT7 ?BOX3 ?LOCATION4 ?LOCATION8 ) 
				) 
			)
		)
		( FORALL
			( ?AGENT7 - AGENT ?AGENT8 - AGENT ?AGENT9 - AGENT ?AGENT10 - AGENT ?LOCATION11 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION5 ?LOCATION11 ) )
					( P-4-PUSH-BOX ?AGENT7 ?AGENT8 ?AGENT9 ?AGENT10 ?BOX3 ?LOCATION4 ?LOCATION11 ) 
				)
			)
		)
	)
  :EFFECT
	( AND
		( POS-AGENT-AT-LOC ?AGENT0 ?LOCATION5 )
		( POS-AGENT-AT-LOC ?AGENT1 ?LOCATION5 )
		( POS-AGENT-AT-LOC ?AGENT2 ?LOCATION5 )
		( POS-BOX-AT-LOC ?BOX3 ?LOCATION5 )
		( NEG-AGENT-AT-LOC ?AGENT0 ?LOCATION4 )
		( NEG-AGENT-AT-LOC ?AGENT1 ?LOCATION4 )
		( NEG-AGENT-AT-LOC ?AGENT2 ?LOCATION4 )
		( NEG-BOX-AT-LOC ?BOX3 ?LOCATION4 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( TAKEN ?AGENT2 )
		( P-3-PUSH-BOX ?AGENT0 ?AGENT1 ?AGENT2 ?BOX3 ?LOCATION4 ?LOCATION5 )
		( P-PUSH-BOX ?AGENT0 ?BOX3 ?LOCATION4 ?LOCATION5 )
		( P-PUSH-BOX ?AGENT1 ?BOX3 ?LOCATION4 ?LOCATION5 )
		( P-PUSH-BOX ?AGENT2 ?BOX3 ?LOCATION4 ?LOCATION5 )
	)
)
( :ACTION 4-PUSH-BOX
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?AGENT3 - AGENT ?BOX4 - BOX ?LOCATION5 - LOCATION ?LOCATION6 - LOCATION )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION5 )
		( AGENT-AT-LOC ?AGENT1 ?LOCATION5 )
		( AGENT-AT-LOC ?AGENT2 ?LOCATION5 )
		( AGENT-AT-LOC ?AGENT3 ?LOCATION5 )
		( BOX-AT-LOC ?BOX4 ?LOCATION5 )
		( CONNECTED ?LOCATION5 ?LOCATION6 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TIRED ?AGENT1 ) )
		( NOT ( TIRED ?AGENT2 ) )
		( NOT ( TIRED ?AGENT3 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT2 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT3 ) )
		( NOT ( SAME-AGENT ?AGENT2 ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT3 ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT2 ?AGENT3 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT2 ) )
		( NOT ( TAKEN ?AGENT3 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT7 - AGENT )
			( NOT ( P-PUSH-BOX ?AGENT7 ?BOX4 ?LOCATION5 ?LOCATION6 ) )
		)
		( FORALL
			( ?AGENT5 - AGENT ?LOCATION7 - LOCATION )
			( OR ( NOT ( = ?LOCATION6 ?LOCATION7 ) )
				( NOT ( P-PUSH-BOX ?AGENT5 ?BOX4 ?LOCATION5 ?LOCATION7 ) ) 
			)
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?LOCATION7 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION6 ?LOCATION7 ) )
					( P-2-PUSH-BOX ?AGENT5 ?AGENT6 ?BOX4 ?LOCATION5 ?LOCATION7 ) 
				) 
			)
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?AGENT7 - AGENT ?LOCATION8 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION6 ?LOCATION8 ) )
					( P-3-PUSH-BOX ?AGENT5 ?AGENT6 ?AGENT7 ?BOX4 ?LOCATION5 ?LOCATION8 ) 
				) 
			)
		)
		( FORALL
			( ?AGENT7 - AGENT ?AGENT8 - AGENT ?AGENT9 - AGENT ?AGENT10 - AGENT ?LOCATION11 - LOCATION )
			( NOT ( AND ( NOT ( = ?LOCATION6 ?LOCATION11 ) )
					( P-4-PUSH-BOX ?AGENT7 ?AGENT8 ?AGENT9 ?AGENT10 ?BOX4 ?LOCATION5 ?LOCATION11 ) 
				)
			)
		)
	)
  :EFFECT
	( AND
		( POS-AGENT-AT-LOC ?AGENT0 ?LOCATION6 )
		( POS-AGENT-AT-LOC ?AGENT1 ?LOCATION6 )
		( POS-AGENT-AT-LOC ?AGENT2 ?LOCATION6 )
		( POS-AGENT-AT-LOC ?AGENT3 ?LOCATION6 )
		( POS-BOX-AT-LOC ?BOX4 ?LOCATION6 )
		( NEG-AGENT-AT-LOC ?AGENT0 ?LOCATION5 )
		( NEG-AGENT-AT-LOC ?AGENT1 ?LOCATION5 )
		( NEG-AGENT-AT-LOC ?AGENT2 ?LOCATION5 )
		( NEG-AGENT-AT-LOC ?AGENT3 ?LOCATION5 )
		( NEG-BOX-AT-LOC ?BOX4 ?LOCATION5 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( TAKEN ?AGENT2 )
		( TAKEN ?AGENT3 )
		( P-4-PUSH-BOX ?AGENT0 ?AGENT1 ?AGENT2 ?AGENT3 ?BOX4 ?LOCATION5 ?LOCATION6 )
		( P-PUSH-BOX ?AGENT0 ?BOX4 ?LOCATION5 ?LOCATION6 )
		( P-PUSH-BOX ?AGENT1 ?BOX4 ?LOCATION5 ?LOCATION6 )
		( P-PUSH-BOX ?AGENT2 ?BOX4 ?LOCATION5 ?LOCATION6 )
		( P-PUSH-BOX ?AGENT3 ?BOX4 ?LOCATION5 ?LOCATION6 )
	)
)
( :ACTION MULTI-END
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( NEG-IN-JOINT )
		( FORALL
			( ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
			( NOT ( P-MOVE-AGENT ?AGENT0 ?LOCATION1 ?LOCATION2 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?BOX1 - BOX ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
			( NOT ( P-PUSH-BOX ?AGENT0 ?BOX1 ?LOCATION2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?BOX2 - BOX ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION )
			( NOT ( P-2-PUSH-BOX ?AGENT0 ?AGENT1 ?BOX2 ?LOCATION3 ?LOCATION4 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?BOX3 - BOX ?LOCATION4 - LOCATION ?LOCATION5 - LOCATION )
			( NOT ( P-3-PUSH-BOX ?AGENT0 ?AGENT1 ?AGENT2 ?BOX3 ?LOCATION4 ?LOCATION5 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?AGENT3 - AGENT ?BOX4 - BOX ?LOCATION5 - LOCATION ?LOCATION6 - LOCATION )
			( NOT ( P-4-PUSH-BOX ?AGENT0 ?AGENT1 ?AGENT2 ?AGENT3 ?BOX4 ?LOCATION5 ?LOCATION6 ) )
		)
		( FORALL
			( ?BOX1 - BOX ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION ) 
			( NOT ( PPP ?BOX1 ?LOCATION2 ?LOCATION3 ) )
		) 
		( FORALL
			( ?BOX0 - BOX ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-BOX-AT-LOC ?BOX0 ?LOCATION1 )
					( AND
						( BOX-AT-LOC ?BOX0 ?LOCATION1 )
						( NOT ( POS-BOX-AT-LOC ?BOX0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?BOX0 - BOX ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-BOX-AT-LOC ?BOX0 ?LOCATION1 )
					( AND
						( NOT ( BOX-AT-LOC ?BOX0 ?LOCATION1 ) )
						( NOT ( NEG-BOX-AT-LOC ?BOX0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-AGENT-AT-LOC ?AGENT0 ?LOCATION1 )
					( AND
						( AGENT-AT-LOC ?AGENT0 ?LOCATION1 )
						( NOT ( POS-AGENT-AT-LOC ?AGENT0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-AGENT-AT-LOC ?AGENT0 ?LOCATION1 )
					( AND
						( NOT ( AGENT-AT-LOC ?AGENT0 ?LOCATION1 ) )
						( NOT ( NEG-AGENT-AT-LOC ?AGENT0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-CONNECTED ?LOCATION0 ?LOCATION1 )
					( AND
						( CONNECTED ?LOCATION0 ?LOCATION1 )
						( NOT ( POS-CONNECTED ?LOCATION0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-CONNECTED ?LOCATION0 ?LOCATION1 )
					( AND
						( NOT ( CONNECTED ?LOCATION0 ?LOCATION1 ) )
						( NOT ( NEG-CONNECTED ?LOCATION0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( AND
				( WHEN
					( POS-TIRED ?AGENT0 )
					( AND
						( TIRED ?AGENT0 )
						( NOT ( POS-TIRED ?AGENT0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( AND
				( WHEN
					( NEG-TIRED ?AGENT0 )
					( AND
						( NOT ( TIRED ?AGENT0 ) )
						( NOT ( NEG-TIRED ?AGENT0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT )
			( AND
				( WHEN
					( POS-SAME-AGENT ?AGENT0 ?AGENT1 )
					( AND
						( SAME-AGENT ?AGENT0 ?AGENT1 )
						( NOT ( POS-SAME-AGENT ?AGENT0 ?AGENT1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT )
			( AND
				( WHEN
					( NEG-SAME-AGENT ?AGENT0 ?AGENT1 )
					( AND
						( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
						( NOT ( NEG-SAME-AGENT ?AGENT0 ?AGENT1 ) )
					)
				)
			)
		)
		( FORALL
			( ?BOX0 - BOX )
			( AND
				( WHEN
					( POS-INTACT ?BOX0 )
					( AND
						( INTACT ?BOX0 )
						( NOT ( POS-INTACT ?BOX0 ) )
					)
				)
			)
		)
		( FORALL
			( ?BOX0 - BOX )
			( AND
				( WHEN
					( NEG-INTACT ?BOX0 )
					( AND
						( NOT ( INTACT ?BOX0 ) )
						( NOT ( NEG-INTACT ?BOX0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( NOT ( TAKEN ?AGENT0 ) )
		)
	)
)
)

;The domain compilation time is: 0.005118

