;;
;;	TABLEMOVER DOMAIN 
;;
( DEFINE ( DOMAIN TABLEMOVER )
( :REQUIREMENTS :CONDITIONAL-EFFECTS :TYPING )
( :TYPES
	OBJECT - OBJECT
	AGENT - OBJECT
	TABLE - OBJECT
	ROOM - OBJECT
)
( :PREDICATES
	( LIFTING ?AGENT0 - AGENT ?TABLE1 - TABLE )
	( POS-LIFTING ?AGENT0 - AGENT ?TABLE1 - TABLE )
	( NEG-LIFTING ?AGENT0 - AGENT ?TABLE1 - TABLE )
	( INROOM ?TABLE0 - TABLE ?ROOM1 - ROOM )
	( POS-INROOM ?TABLE0 - TABLE ?ROOM1 - ROOM )
	( NEG-INROOM ?TABLE0 - TABLE ?ROOM1 - ROOM )
	( IN ?AGENT0 - AGENT ?ROOM1 - ROOM )
	( POS-IN ?AGENT0 - AGENT ?ROOM1 - ROOM )
	( NEG-IN ?AGENT0 - AGENT ?ROOM1 - ROOM )
	( CONNECTED ?ROOM0 - ROOM ?ROOM1 - ROOM )
	( POS-CONNECTED ?ROOM0 - ROOM ?ROOM1 - ROOM )
	( NEG-CONNECTED ?ROOM0 - ROOM ?ROOM1 - ROOM )
	( INTACT ?TABLE0 - TABLE )
	( POS-INTACT ?TABLE0 - TABLE )
	( NEG-INTACT ?TABLE0 - TABLE )
	( HAS-CHARGING-POINT ?ROOM0 - ROOM )
	( POS-HAS-CHARGING-POINT ?ROOM0 - ROOM )
	( NEG-HAS-CHARGING-POINT ?ROOM0 - ROOM )
	( AVAILABLE ?AGENT0 - AGENT )
	( POS-AVAILABLE ?AGENT0 - AGENT )
	( NEG-AVAILABLE ?AGENT0 - AGENT )
	( CHARGED ?AGENT0 - AGENT )
	( POS-CHARGED ?AGENT0 - AGENT )
	( NEG-CHARGED ?AGENT0 - AGENT )
	( SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( POS-SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( NEG-SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( TAKEN ?AGENT0 - AGENT )
	( NEG-IN-JOINT )
	( P-MOVE-AGENT ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM )
	( P-CHARGE-AGENT ?AGENT0 - AGENT ?ROOM1 - ROOM )
	( P-MOVE-TABLE ?AGENT0 - AGENT ?TABLE1 - TABLE ?ROOM2 - ROOM ?ROOM3 - ROOM )
	( P-2-MOVE-TABLE ?AGENT0 - AGENT ?AGENT1 - AGENT ?TABLE2 - TABLE ?ROOM3 - ROOM ?ROOM4 - ROOM )
	( P-3-MOVE-TABLE ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?TABLE3 - TABLE ?ROOM4 - ROOM ?ROOM5 - ROOM )
	( P-LIFT-TABLE ?AGENT0 - AGENT ?TABLE1 - TABLE ?ROOM2 - ROOM )
	( P-2-LIFT-TABLE ?AGENT0 - AGENT ?AGENT1 - AGENT ?TABLE2 - TABLE ?ROOM3 - ROOM )
	( P-3-LIFT-TABLE ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?TABLE3 - TABLE ?ROOM4 - ROOM )
	( P-DROP-TABLE ?AGENT0 - AGENT ?TABLE1 - TABLE ?ROOM2 - ROOM )
	( P-2-DROP-TABLE ?AGENT0 - AGENT ?AGENT1 - AGENT ?TABLE2 - TABLE ?ROOM3 - ROOM )
	( P-3-DROP-TABLE ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?TABLE3 - TABLE ?ROOM4 - ROOM )
)
( :ACTION MULTI-START
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( NEG-IN-JOINT )
	)
  :EFFECT
	( AND
		( NOT ( NEG-IN-JOINT ) )
	)
)
( :ACTION MOVE-AGENT
  :PARAMETERS ( ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( IN ?AGENT0 ?ROOM1 )
		( CONNECTED ?ROOM1 ?ROOM2 )
		( AVAILABLE ?AGENT0 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( NEG-IN ?AGENT0 ?ROOM1 )
		( POS-IN ?AGENT0 ?ROOM2 )
		( TAKEN ?AGENT0 )
		( P-MOVE-AGENT ?AGENT0 ?ROOM1 ?ROOM2 )
	)
)
( :ACTION CHARGE-AGENT
  :PARAMETERS ( ?AGENT0 - AGENT ?ROOM1 - ROOM )
  :PRECONDITION
	( AND
		( IN ?AGENT0 ?ROOM1 )
		( HAS-CHARGING-POINT ?ROOM1 )
		( NOT ( CHARGED ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( POS-CHARGED ?AGENT0 )
		( TAKEN ?AGENT0 )
		( P-CHARGE-AGENT ?AGENT0 ?ROOM1 )
	)
)
( :ACTION MOVE-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?TABLE1 - TABLE ?ROOM2 - ROOM ?ROOM3 - ROOM )
  :PRECONDITION
	( AND
		( LIFTING ?AGENT0 ?TABLE1 )
		( IN ?AGENT0 ?ROOM2 )
		( CONNECTED ?ROOM2 ?ROOM3 )
		( CHARGED ?AGENT0 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( P-MOVE-TABLE ?AGENT4 ?TABLE1 ?ROOM2 ?ROOM3 ) )
		)
	)
  :EFFECT
	( AND
		( NEG-IN ?AGENT0 ?ROOM2 )
		( POS-IN ?AGENT0 ?ROOM3 )
		( NEG-CHARGED ?AGENT0 )
		( TAKEN ?AGENT0 )
		( P-MOVE-TABLE ?AGENT0 ?TABLE1 ?ROOM2 ?ROOM3 )
	)
)
( :ACTION 2-MOVE-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?TABLE2 - TABLE ?ROOM3 - ROOM ?ROOM4 - ROOM )
  :PRECONDITION
	( AND
		( LIFTING ?AGENT0 ?TABLE2 )
		( LIFTING ?AGENT1 ?TABLE2 )
		( IN ?AGENT0 ?ROOM3 )
		( IN ?AGENT1 ?ROOM3 )
		( CONNECTED ?ROOM3 ?ROOM4 )
		( CHARGED ?AGENT0 )
		( CHARGED ?AGENT1 )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT5 - AGENT )
			( NOT ( P-MOVE-TABLE ?AGENT5 ?TABLE2 ?ROOM3 ?ROOM4 ) )
		)
	)
  :EFFECT
	( AND
		( NEG-IN ?AGENT0 ?ROOM3 )
		( NEG-IN ?AGENT1 ?ROOM3 )
		( POS-IN ?AGENT0 ?ROOM4 )
		( POS-IN ?AGENT1 ?ROOM4 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( P-2-MOVE-TABLE ?AGENT0 ?AGENT1 ?TABLE2 ?ROOM3 ?ROOM4 )
		( P-MOVE-TABLE ?AGENT0 ?TABLE2 ?ROOM3 ?ROOM4 )
		( P-MOVE-TABLE ?AGENT1 ?TABLE2 ?ROOM3 ?ROOM4 )
	)
)
( :ACTION 3-MOVE-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?TABLE3 - TABLE ?ROOM4 - ROOM ?ROOM5 - ROOM )
  :PRECONDITION
	( AND
		( LIFTING ?AGENT0 ?TABLE3 )
		( LIFTING ?AGENT1 ?TABLE3 )
		( LIFTING ?AGENT2 ?TABLE3 )
		( IN ?AGENT0 ?ROOM4 )
		( IN ?AGENT1 ?ROOM4 )
		( IN ?AGENT2 ?ROOM4 )
		( CONNECTED ?ROOM4 ?ROOM5 )
		( CHARGED ?AGENT0 )
		( CHARGED ?AGENT1 )
		( CHARGED ?AGENT2 )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT2 ) )
		( NOT ( SAME-AGENT ?AGENT2 ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT2 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT6 - AGENT )
			( NOT ( P-MOVE-TABLE ?AGENT6 ?TABLE3 ?ROOM4 ?ROOM5 ) )
		)
	)
  :EFFECT
	( AND
		( NEG-IN ?AGENT0 ?ROOM4 )
		( NEG-IN ?AGENT1 ?ROOM4 )
		( NEG-IN ?AGENT2 ?ROOM4 )
		( POS-IN ?AGENT0 ?ROOM5 )
		( POS-IN ?AGENT1 ?ROOM5 )
		( POS-IN ?AGENT2 ?ROOM5 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( TAKEN ?AGENT2 )
		( P-3-MOVE-TABLE ?AGENT0 ?AGENT1 ?AGENT2 ?TABLE3 ?ROOM4 ?ROOM5 )
		( P-MOVE-TABLE ?AGENT0 ?TABLE3 ?ROOM4 ?ROOM5 )
		( P-MOVE-TABLE ?AGENT1 ?TABLE3 ?ROOM4 ?ROOM5 )
		( P-MOVE-TABLE ?AGENT2 ?TABLE3 ?ROOM4 ?ROOM5 )
	)
)
( :ACTION LIFT-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?TABLE1 - TABLE ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( AVAILABLE ?AGENT0 )
		( IN ?AGENT0 ?ROOM2 )
		( INROOM ?TABLE1 ?ROOM2 )
		( INTACT ?TABLE1 )
		( CHARGED ?AGENT0 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT3 - AGENT )
			( NOT ( P-LIFT-TABLE ?AGENT3 ?TABLE1 ?ROOM2 ) )
		)
	)
  :EFFECT
	( AND
		( POS-LIFTING ?AGENT0 ?TABLE1 )
		( NEG-AVAILABLE ?AGENT0 )
		( NEG-INROOM ?TABLE1 ?ROOM2 )
		( NEG-INTACT ?TABLE1 )
		( TAKEN ?AGENT0 )
		( P-LIFT-TABLE ?AGENT0 ?TABLE1 ?ROOM2 )
	)
)
( :ACTION 2-LIFT-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?TABLE2 - TABLE ?ROOM3 - ROOM )
  :PRECONDITION
	( AND
		( AVAILABLE ?AGENT0 )
		( AVAILABLE ?AGENT1 )
		( IN ?AGENT0 ?ROOM3 )
		( IN ?AGENT1 ?ROOM3 )
		( INROOM ?TABLE2 ?ROOM3 )
		( INTACT ?TABLE2 )
		( CHARGED ?AGENT0 )
		( CHARGED ?AGENT1 )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( P-LIFT-TABLE ?AGENT4 ?TABLE2 ?ROOM3 ) )
		)
	)
  :EFFECT
	( AND
		( POS-LIFTING ?AGENT0 ?TABLE2 )
		( POS-LIFTING ?AGENT1 ?TABLE2 )
		( NEG-AVAILABLE ?AGENT0 )
		( NEG-AVAILABLE ?AGENT1 )
		( NEG-INROOM ?TABLE2 ?ROOM3 )
		( POS-INTACT ?TABLE2 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( P-2-LIFT-TABLE ?AGENT0 ?AGENT1 ?TABLE2 ?ROOM3 )
		( P-LIFT-TABLE ?AGENT0 ?TABLE2 ?ROOM3 )
		( P-LIFT-TABLE ?AGENT1 ?TABLE2 ?ROOM3 )
	)
)
( :ACTION 3-LIFT-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?TABLE3 - TABLE ?ROOM4 - ROOM )
  :PRECONDITION
	( AND
		( AVAILABLE ?AGENT0 )
		( AVAILABLE ?AGENT1 )
		( AVAILABLE ?AGENT2 )
		( IN ?AGENT0 ?ROOM4 )
		( IN ?AGENT1 ?ROOM4 )
		( IN ?AGENT2 ?ROOM4 )
		( INROOM ?TABLE3 ?ROOM4 )
		( INTACT ?TABLE3 )
		( CHARGED ?AGENT0 )
		( CHARGED ?AGENT1 )
		( CHARGED ?AGENT2 )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT2 ) )
		( NOT ( SAME-AGENT ?AGENT2 ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT2 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT5 - AGENT )
			( NOT ( P-LIFT-TABLE ?AGENT5 ?TABLE3 ?ROOM4 ) )
		)
	)
  :EFFECT
	( AND
		( POS-LIFTING ?AGENT0 ?TABLE3 )
		( POS-LIFTING ?AGENT1 ?TABLE3 )
		( POS-LIFTING ?AGENT2 ?TABLE3 )
		( NEG-AVAILABLE ?AGENT0 )
		( NEG-AVAILABLE ?AGENT1 )
		( NEG-AVAILABLE ?AGENT2 )
		( NEG-INROOM ?TABLE3 ?ROOM4 )
		( POS-INTACT ?TABLE3 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( TAKEN ?AGENT2 )
		( P-3-LIFT-TABLE ?AGENT0 ?AGENT1 ?AGENT2 ?TABLE3 ?ROOM4 )
		( P-LIFT-TABLE ?AGENT0 ?TABLE3 ?ROOM4 )
		( P-LIFT-TABLE ?AGENT1 ?TABLE3 ?ROOM4 )
		( P-LIFT-TABLE ?AGENT2 ?TABLE3 ?ROOM4 )
	)
)
( :ACTION DROP-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?TABLE1 - TABLE ?ROOM2 - ROOM )
  :PRECONDITION
	( AND
		( IN ?AGENT0 ?ROOM2 )
		( LIFTING ?AGENT0 ?TABLE1 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT3 - AGENT )
			( NOT ( P-DROP-TABLE ?AGENT3 ?TABLE1 ?ROOM2 ) )
		)
	)
  :EFFECT
	( AND
		( NEG-LIFTING ?AGENT0 ?TABLE1 )
		( POS-INROOM ?TABLE1 ?ROOM2 )
		( POS-AVAILABLE ?AGENT0 )
		( NEG-INTACT ?TABLE1 )
		( NEG-CHARGED ?AGENT0 )
		( TAKEN ?AGENT0 )
		( P-DROP-TABLE ?AGENT0 ?TABLE1 ?ROOM2 )
	)
)
( :ACTION 2-DROP-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?TABLE2 - TABLE ?ROOM3 - ROOM )
  :PRECONDITION
	( AND
		( IN ?AGENT0 ?ROOM3 )
		( IN ?AGENT1 ?ROOM3 )
		( LIFTING ?AGENT0 ?TABLE2 )
		( LIFTING ?AGENT1 ?TABLE2 )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( P-DROP-TABLE ?AGENT4 ?TABLE2 ?ROOM3 ) )
		)
	)
  :EFFECT
	( AND
		( NEG-LIFTING ?AGENT0 ?TABLE2 )
		( NEG-LIFTING ?AGENT1 ?TABLE2 )
		( POS-INROOM ?TABLE2 ?ROOM3 )
		( POS-AVAILABLE ?AGENT0 )
		( POS-AVAILABLE ?AGENT1 )
		( POS-INTACT ?TABLE2 )
		( NEG-CHARGED ?AGENT0 )
		( NEG-CHARGED ?AGENT1 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( P-2-DROP-TABLE ?AGENT0 ?AGENT1 ?TABLE2 ?ROOM3 )
		( P-DROP-TABLE ?AGENT0 ?TABLE2 ?ROOM3 )
		( P-DROP-TABLE ?AGENT1 ?TABLE2 ?ROOM3 )
	)
)
( :ACTION 3-DROP-TABLE
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?TABLE3 - TABLE ?ROOM4 - ROOM )
  :PRECONDITION
	( AND
		( IN ?AGENT0 ?ROOM4 )
		( IN ?AGENT1 ?ROOM4 )
		( IN ?AGENT2 ?ROOM4 )
		( LIFTING ?AGENT0 ?TABLE3 )
		( LIFTING ?AGENT1 ?TABLE3 )
		( LIFTING ?AGENT2 ?TABLE3 )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT2 ) )
		( NOT ( SAME-AGENT ?AGENT2 ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT2 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT5 - AGENT )
			( NOT ( P-DROP-TABLE ?AGENT5 ?TABLE3 ?ROOM4 ) )
		)
	)
  :EFFECT
	( AND
		( NEG-LIFTING ?AGENT0 ?TABLE3 )
		( NEG-LIFTING ?AGENT1 ?TABLE3 )
		( NEG-LIFTING ?AGENT2 ?TABLE3 )
		( POS-INROOM ?TABLE3 ?ROOM4 )
		( POS-AVAILABLE ?AGENT0 )
		( POS-AVAILABLE ?AGENT1 )
		( POS-AVAILABLE ?AGENT2 )
		( POS-INTACT ?TABLE3 )
		( NEG-CHARGED ?AGENT0 )
		( NEG-CHARGED ?AGENT1 )
		( NEG-CHARGED ?AGENT2 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( TAKEN ?AGENT2 )
		( P-3-DROP-TABLE ?AGENT0 ?AGENT1 ?AGENT2 ?TABLE3 ?ROOM4 )
		( P-DROP-TABLE ?AGENT0 ?TABLE3 ?ROOM4 )
		( P-DROP-TABLE ?AGENT1 ?TABLE3 ?ROOM4 )
		( P-DROP-TABLE ?AGENT2 ?TABLE3 ?ROOM4 )
	)
)
( :ACTION MULTI-END
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( NEG-IN-JOINT )
		( FORALL
			( ?AGENT0 - AGENT ?ROOM1 - ROOM ?ROOM2 - ROOM )
			( NOT ( P-MOVE-AGENT ?AGENT0 ?ROOM1 ?ROOM2 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?ROOM1 - ROOM )
			( NOT ( P-CHARGE-AGENT ?AGENT0 ?ROOM1 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?TABLE1 - TABLE ?ROOM2 - ROOM ?ROOM3 - ROOM )
			( NOT ( P-MOVE-TABLE ?AGENT0 ?TABLE1 ?ROOM2 ?ROOM3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?TABLE2 - TABLE ?ROOM3 - ROOM ?ROOM4 - ROOM )
			( NOT ( P-2-MOVE-TABLE ?AGENT0 ?AGENT1 ?TABLE2 ?ROOM3 ?ROOM4 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?TABLE3 - TABLE ?ROOM4 - ROOM ?ROOM5 - ROOM )
			( NOT ( P-3-MOVE-TABLE ?AGENT0 ?AGENT1 ?AGENT2 ?TABLE3 ?ROOM4 ?ROOM5 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?TABLE1 - TABLE ?ROOM2 - ROOM )
			( NOT ( P-LIFT-TABLE ?AGENT0 ?TABLE1 ?ROOM2 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?TABLE2 - TABLE ?ROOM3 - ROOM )
			( NOT ( P-2-LIFT-TABLE ?AGENT0 ?AGENT1 ?TABLE2 ?ROOM3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?TABLE3 - TABLE ?ROOM4 - ROOM )
			( NOT ( P-3-LIFT-TABLE ?AGENT0 ?AGENT1 ?AGENT2 ?TABLE3 ?ROOM4 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?TABLE1 - TABLE ?ROOM2 - ROOM )
			( NOT ( P-DROP-TABLE ?AGENT0 ?TABLE1 ?ROOM2 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?TABLE2 - TABLE ?ROOM3 - ROOM )
			( NOT ( P-2-DROP-TABLE ?AGENT0 ?AGENT1 ?TABLE2 ?ROOM3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?TABLE3 - TABLE ?ROOM4 - ROOM )
			( NOT ( P-3-DROP-TABLE ?AGENT0 ?AGENT1 ?AGENT2 ?TABLE3 ?ROOM4 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?TABLE1 - TABLE )
			( AND
				( WHEN
					( POS-LIFTING ?AGENT0 ?TABLE1 )
					( AND
						( LIFTING ?AGENT0 ?TABLE1 )
						( NOT ( POS-LIFTING ?AGENT0 ?TABLE1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?TABLE1 - TABLE )
			( AND
				( WHEN
					( NEG-LIFTING ?AGENT0 ?TABLE1 )
					( AND
						( NOT ( LIFTING ?AGENT0 ?TABLE1 ) )
						( NOT ( NEG-LIFTING ?AGENT0 ?TABLE1 ) )
					)
				)
			)
		)
		( FORALL
			( ?TABLE0 - TABLE ?ROOM1 - ROOM )
			( AND
				( WHEN
					( POS-INROOM ?TABLE0 ?ROOM1 )
					( AND
						( INROOM ?TABLE0 ?ROOM1 )
						( NOT ( POS-INROOM ?TABLE0 ?ROOM1 ) )
					)
				)
			)
		)
		( FORALL
			( ?TABLE0 - TABLE ?ROOM1 - ROOM )
			( AND
				( WHEN
					( NEG-INROOM ?TABLE0 ?ROOM1 )
					( AND
						( NOT ( INROOM ?TABLE0 ?ROOM1 ) )
						( NOT ( NEG-INROOM ?TABLE0 ?ROOM1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?ROOM1 - ROOM )
			( AND
				( WHEN
					( POS-IN ?AGENT0 ?ROOM1 )
					( AND
						( IN ?AGENT0 ?ROOM1 )
						( NOT ( POS-IN ?AGENT0 ?ROOM1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?ROOM1 - ROOM )
			( AND
				( WHEN
					( NEG-IN ?AGENT0 ?ROOM1 )
					( AND
						( NOT ( IN ?AGENT0 ?ROOM1 ) )
						( NOT ( NEG-IN ?AGENT0 ?ROOM1 ) )
					)
				)
			)
		)
		( FORALL
			( ?ROOM0 - ROOM ?ROOM1 - ROOM )
			( AND
				( WHEN
					( POS-CONNECTED ?ROOM0 ?ROOM1 )
					( AND
						( CONNECTED ?ROOM0 ?ROOM1 )
						( NOT ( POS-CONNECTED ?ROOM0 ?ROOM1 ) )
					)
				)
			)
		)
		( FORALL
			( ?ROOM0 - ROOM ?ROOM1 - ROOM )
			( AND
				( WHEN
					( NEG-CONNECTED ?ROOM0 ?ROOM1 )
					( AND
						( NOT ( CONNECTED ?ROOM0 ?ROOM1 ) )
						( NOT ( NEG-CONNECTED ?ROOM0 ?ROOM1 ) )
					)
				)
			)
		)
		( FORALL
			( ?TABLE0 - TABLE )
			( AND
				( WHEN
					( POS-INTACT ?TABLE0 )
					( AND
						( INTACT ?TABLE0 )
						( NOT ( POS-INTACT ?TABLE0 ) )
					)
				)
			)
		)
		( FORALL
			( ?TABLE0 - TABLE )
			( AND
				( WHEN
					( NEG-INTACT ?TABLE0 )
					( AND
						( NOT ( INTACT ?TABLE0 ) )
						( NOT ( NEG-INTACT ?TABLE0 ) )
					)
				)
			)
		)
		( FORALL
			( ?ROOM0 - ROOM )
			( AND
				( WHEN
					( POS-HAS-CHARGING-POINT ?ROOM0 )
					( AND
						( HAS-CHARGING-POINT ?ROOM0 )
						( NOT ( POS-HAS-CHARGING-POINT ?ROOM0 ) )
					)
				)
			)
		)
		( FORALL
			( ?ROOM0 - ROOM )
			( AND
				( WHEN
					( NEG-HAS-CHARGING-POINT ?ROOM0 )
					( AND
						( NOT ( HAS-CHARGING-POINT ?ROOM0 ) )
						( NOT ( NEG-HAS-CHARGING-POINT ?ROOM0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( AND
				( WHEN
					( POS-AVAILABLE ?AGENT0 )
					( AND
						( AVAILABLE ?AGENT0 )
						( NOT ( POS-AVAILABLE ?AGENT0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( AND
				( WHEN
					( NEG-AVAILABLE ?AGENT0 )
					( AND
						( NOT ( AVAILABLE ?AGENT0 ) )
						( NOT ( NEG-AVAILABLE ?AGENT0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( AND
				( WHEN
					( POS-CHARGED ?AGENT0 )
					( AND
						( CHARGED ?AGENT0 )
						( NOT ( POS-CHARGED ?AGENT0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( AND
				( WHEN
					( NEG-CHARGED ?AGENT0 )
					( AND
						( NOT ( CHARGED ?AGENT0 ) )
						( NOT ( NEG-CHARGED ?AGENT0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT )
			( AND
				( WHEN
					( POS-SAME-AGENT ?AGENT0 ?AGENT1 )
					( AND
						( SAME-AGENT ?AGENT0 ?AGENT1 )
						( NOT ( POS-SAME-AGENT ?AGENT0 ?AGENT1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT )
			( AND
				( WHEN
					( NEG-SAME-AGENT ?AGENT0 ?AGENT1 )
					( AND
						( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
						( NOT ( NEG-SAME-AGENT ?AGENT0 ?AGENT1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( NOT ( TAKEN ?AGENT0 ) )
		)
	)
)
)

;The domain compilation time is: 0.008718

