;;
;;	MAZE DOMAIN 
;;
( DEFINE ( DOMAIN MAZE )
( :REQUIREMENTS :TYPING )
( :TYPES
	OBJECT - OBJECT
	AGENT - OBJECT
	LOCATION - OBJECT
	DOOR - OBJECT
	BRIDGE - OBJECT
	BOAT - OBJECT
	SWITCH - OBJECT
)
( :PREDICATES
	( AT ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( POS-AT ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( NEG-AT ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( HAS-SWITCH ?SWITCH0 - SWITCH ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( POS-HAS-SWITCH ?SWITCH0 - SWITCH ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( NEG-HAS-SWITCH ?SWITCH0 - SWITCH ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( BLOCKED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( POS-BLOCKED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( NEG-BLOCKED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( HAS-DOOR ?DOOR0 - DOOR ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( POS-HAS-DOOR ?DOOR0 - DOOR ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( NEG-HAS-DOOR ?DOOR0 - DOOR ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( HAS-BOAT ?BOAT0 - BOAT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( POS-HAS-BOAT ?BOAT0 - BOAT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( NEG-HAS-BOAT ?BOAT0 - BOAT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( AT-BOAT ?BOAT0 - BOAT ?LOCATION1 - LOCATION )
	( POS-AT-BOAT ?BOAT0 - BOAT ?LOCATION1 - LOCATION )
	( NEG-AT-BOAT ?BOAT0 - BOAT ?LOCATION1 - LOCATION )
	( HAS-BRIDGE ?BRIDGE0 - BRIDGE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( POS-HAS-BRIDGE ?BRIDGE0 - BRIDGE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( NEG-HAS-BRIDGE ?BRIDGE0 - BRIDGE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( POS-SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( NEG-SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( TAKEN ?AGENT0 - AGENT )
	( NEG-IN-JOINT )
	( P-MOVE ?AGENT0 - AGENT ?DOOR1 - DOOR ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( P-ROW ?AGENT0 - AGENT ?BOAT1 - BOAT ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( P-2-ROW ?AGENT0 - AGENT ?AGENT1 - AGENT ?BOAT2 - BOAT ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION )
	( P-3-ROW ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?BOAT3 - BOAT ?LOCATION4 - LOCATION ?LOCATION5 - LOCATION )
	( P-CROSS ?AGENT0 - AGENT ?BRIDGE1 - BRIDGE ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( P-PUSHSWITCH ?AGENT0 - AGENT ?SWITCH1 - SWITCH ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION )
	( PPP ?BOAT1 - BOAT ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION ) 
)
( :ACTION MULTI-START
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( NEG-IN-JOINT )
	)
  :EFFECT
	( AND
		( NOT ( NEG-IN-JOINT ) )
	)
)
( :ACTION MOVE
  :PARAMETERS ( ?AGENT0 - AGENT ?DOOR1 - DOOR ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?AGENT0 ?LOCATION2 )
		( NOT ( BLOCKED ?LOCATION2 ?LOCATION3 ) )
		( HAS-DOOR ?DOOR1 ?LOCATION2 ?LOCATION3 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( POS-AT ?AGENT0 ?LOCATION3 )
		( NEG-AT ?AGENT0 ?LOCATION2 )
		( TAKEN ?AGENT0 )
		( P-MOVE ?AGENT0 ?DOOR1 ?LOCATION2 ?LOCATION3 )
	)
)
( :ACTION ROW
  :PARAMETERS ( ?AGENT0 - AGENT ?BOAT1 - BOAT ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?AGENT0 ?LOCATION2 )
		( HAS-BOAT ?BOAT1 ?LOCATION2 ?LOCATION3 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
		( PPP ?BOAT1 ?LOCATION2 ?LOCATION3 )
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( P-ROW ?AGENT4 ?BOAT1 ?LOCATION2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT5 - AGENT ?LOCATION6 - LOCATION )
			( OR ( NOT ( = ?LOCATION3 ?LOCATION6 ) )
				( NOT ( P-ROW ?AGENT5 ?BOAT1 ?LOCATION2 ?LOCATION6 ) )  
			) 
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?LOCATION7 - LOCATION )
			( OR ( NOT ( = ?LOCATION3 ?LOCATION7 ) )
				( NOT ( P-2-ROW ?AGENT5 ?AGENT6 ?BOAT1 ?LOCATION2 ?LOCATION7 ) ) 
			)
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?AGENT7 - AGENT ?LOCATION8 - LOCATION )
			( OR ( NOT ( = ?LOCATION3 ?LOCATION8 ) )
				( NOT ( P-3-ROW ?AGENT5 ?AGENT6 ?AGENT7 ?BOAT1 ?LOCATION2 ?LOCATION8 ) ) 
			)
		)
	)
  :EFFECT
	( AND
		( POS-AT ?AGENT0 ?LOCATION3 )
		( NEG-AT ?AGENT0 ?LOCATION2 )
		( TAKEN ?AGENT0 )
		( P-ROW ?AGENT0 ?BOAT1 ?LOCATION2 ?LOCATION3 )
	)
)
( :ACTION 2-ROW
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?BOAT2 - BOAT ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?AGENT0 ?LOCATION3 )
		( AT ?AGENT1 ?LOCATION3 )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( HAS-BOAT ?BOAT2 ?LOCATION3 ?LOCATION4 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT5 - AGENT )
			( AND
				( NOT ( P-ROW ?AGENT5 ?BOAT2 ?LOCATION3 ?LOCATION4 ) )
			)
		)
		( FORALL
			( ?AGENT5 - AGENT ?LOCATION6 - LOCATION )
			( OR ( NOT ( = ?LOCATION4 ?LOCATION6 ) )
				( NOT ( P-ROW ?AGENT5 ?BOAT2 ?LOCATION3 ?LOCATION6 ) ) 
			)
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?LOCATION7 - LOCATION )
			( OR ( NOT ( = ?LOCATION4 ?LOCATION7 ) )
				( NOT ( P-2-ROW ?AGENT5 ?AGENT6 ?BOAT2 ?LOCATION3 ?LOCATION7 ) ) 
			)
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?AGENT7 - AGENT ?LOCATION8 - LOCATION )
			( OR ( NOT ( = ?LOCATION4 ?LOCATION8 ) )
				( NOT ( P-3-ROW ?AGENT5 ?AGENT6 ?AGENT7 ?BOAT2 ?LOCATION3 ?LOCATION8 ) ) 
			)
		)
	)
  :EFFECT
	( AND
		( POS-AT ?AGENT0 ?LOCATION4 )
		( POS-AT ?AGENT1 ?LOCATION4 )
		( NEG-AT ?AGENT0 ?LOCATION3 )
		( NEG-AT ?AGENT1 ?LOCATION3 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( PPP ?BOAT2 ?LOCATION3 ?LOCATION4 )
		( P-2-ROW ?AGENT0 ?AGENT1 ?BOAT2 ?LOCATION3 ?LOCATION4 )
		( P-ROW ?AGENT0 ?BOAT2 ?LOCATION3 ?LOCATION4 )
		( P-ROW ?AGENT1 ?BOAT2 ?LOCATION3 ?LOCATION4 )
	)
)
( :ACTION 3-ROW
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?BOAT3 - BOAT ?LOCATION4 - LOCATION ?LOCATION5 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?AGENT0 ?LOCATION4 )
		( AT ?AGENT1 ?LOCATION4 )
		( AT ?AGENT2 ?LOCATION4 )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT2 ) )
		( NOT ( SAME-AGENT ?AGENT2 ?AGENT1 ) )
		( HAS-BOAT ?BOAT3 ?LOCATION4 ?LOCATION5 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT2 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT5 - AGENT ?LOCATION6 - LOCATION )
			( OR ( NOT ( = ?LOCATION5 ?LOCATION6 ) )
				( NOT ( P-ROW ?AGENT5 ?BOAT3 ?LOCATION4 ?LOCATION6 ) ) 
			)
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?LOCATION7 - LOCATION )
			( OR ( NOT ( = ?LOCATION5 ?LOCATION7 ) )
				( NOT ( P-2-ROW ?AGENT5 ?AGENT6 ?BOAT3 ?LOCATION4 ?LOCATION7 ) ) 
			)
		)
		( FORALL
			( ?AGENT5 - AGENT ?AGENT6 - AGENT ?AGENT7 - AGENT ?LOCATION8 - LOCATION )
			( OR ( NOT ( = ?LOCATION5 ?LOCATION8 ) )
				( NOT ( P-3-ROW ?AGENT5 ?AGENT6 ?AGENT7 ?BOAT3 ?LOCATION4 ?LOCATION8 ) ) 
			)
		)
	)
  :EFFECT
	( AND
		( POS-AT ?AGENT0 ?LOCATION5 )
		( POS-AT ?AGENT1 ?LOCATION5 )
		( POS-AT ?AGENT2 ?LOCATION5 )
		( NEG-AT ?AGENT0 ?LOCATION4 )
		( NEG-AT ?AGENT1 ?LOCATION4 )
		( NEG-AT ?AGENT2 ?LOCATION4 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( TAKEN ?AGENT2 )
		( P-3-ROW ?AGENT0 ?AGENT1 ?AGENT2 ?BOAT3 ?LOCATION4 ?LOCATION5 )
		( P-ROW ?AGENT0 ?BOAT3 ?LOCATION4 ?LOCATION5 )
		( P-ROW ?AGENT1 ?BOAT3 ?LOCATION4 ?LOCATION5 )
		( P-ROW ?AGENT2 ?BOAT3 ?LOCATION4 ?LOCATION5 )
	)
)
( :ACTION CROSS
  :PARAMETERS ( ?AGENT0 - AGENT ?BRIDGE1 - BRIDGE ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?AGENT0 ?LOCATION2 )
		( HAS-BRIDGE ?BRIDGE1 ?LOCATION2 ?LOCATION3 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( POS-AT ?AGENT0 ?LOCATION3 )
		( NEG-AT ?AGENT0 ?LOCATION2 )
		( NEG-HAS-BRIDGE ?BRIDGE1 ?LOCATION2 ?LOCATION3 )
		( NEG-HAS-BRIDGE ?BRIDGE1 ?LOCATION3 ?LOCATION2 )
		( TAKEN ?AGENT0 )
		( P-CROSS ?AGENT0 ?BRIDGE1 ?LOCATION2 ?LOCATION3 )
	)
)
( :ACTION PUSHSWITCH
  :PARAMETERS ( ?AGENT0 - AGENT ?SWITCH1 - SWITCH ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION )
  :PRECONDITION
	( AND
		( AT ?AGENT0 ?LOCATION2 )
		( HAS-SWITCH ?SWITCH1 ?LOCATION2 ?LOCATION3 ?LOCATION4 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( NEG-BLOCKED ?LOCATION3 ?LOCATION4 )
		( NEG-BLOCKED ?LOCATION4 ?LOCATION3 )
		( TAKEN ?AGENT0 )
		( P-PUSHSWITCH ?AGENT0 ?SWITCH1 ?LOCATION2 ?LOCATION3 ?LOCATION4 )
	)
)
( :ACTION MULTI-END
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( NEG-IN-JOINT )
		( FORALL
			( ?AGENT0 - AGENT ?DOOR1 - DOOR ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
			( NOT ( P-MOVE ?AGENT0 ?DOOR1 ?LOCATION2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?BOAT1 - BOAT ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
			( NOT ( P-ROW ?AGENT0 ?BOAT1 ?LOCATION2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?BOAT2 - BOAT ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION )
			( NOT ( P-2-ROW ?AGENT0 ?AGENT1 ?BOAT2 ?LOCATION3 ?LOCATION4 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?BOAT3 - BOAT ?LOCATION4 - LOCATION ?LOCATION5 - LOCATION )
			( NOT ( P-3-ROW ?AGENT0 ?AGENT1 ?AGENT2 ?BOAT3 ?LOCATION4 ?LOCATION5 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?BRIDGE1 - BRIDGE ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
			( NOT ( P-CROSS ?AGENT0 ?BRIDGE1 ?LOCATION2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?SWITCH1 - SWITCH ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION )
			( NOT ( P-PUSHSWITCH ?AGENT0 ?SWITCH1 ?LOCATION2 ?LOCATION3 ?LOCATION4 ) )
		)
		( FORALL
			( ?BOAT1 - BOAT ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
			( NOT ( PPP ?BOAT1 ?LOCATION2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-AT ?AGENT0 ?LOCATION1 )
					( AND
						( AT ?AGENT0 ?LOCATION1 )
						( NOT ( POS-AT ?AGENT0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-AT ?AGENT0 ?LOCATION1 )
					( AND
						( NOT ( AT ?AGENT0 ?LOCATION1 ) )
						( NOT ( NEG-AT ?AGENT0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?SWITCH0 - SWITCH ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
			( AND
				( WHEN
					( POS-HAS-SWITCH ?SWITCH0 ?LOCATION1 ?LOCATION2 ?LOCATION3 )
					( AND
						( HAS-SWITCH ?SWITCH0 ?LOCATION1 ?LOCATION2 ?LOCATION3 )
						( NOT ( POS-HAS-SWITCH ?SWITCH0 ?LOCATION1 ?LOCATION2 ?LOCATION3 ) )
					)
				)
			)
		)
		( FORALL
			( ?SWITCH0 - SWITCH ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
			( AND
				( WHEN
					( NEG-HAS-SWITCH ?SWITCH0 ?LOCATION1 ?LOCATION2 ?LOCATION3 )
					( AND
						( NOT ( HAS-SWITCH ?SWITCH0 ?LOCATION1 ?LOCATION2 ?LOCATION3 ) )
						( NOT ( NEG-HAS-SWITCH ?SWITCH0 ?LOCATION1 ?LOCATION2 ?LOCATION3 ) )
					)
				)
			)
		)
		( FORALL
			( ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-BLOCKED ?LOCATION0 ?LOCATION1 )
					( AND
						( BLOCKED ?LOCATION0 ?LOCATION1 )
						( NOT ( POS-BLOCKED ?LOCATION0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-BLOCKED ?LOCATION0 ?LOCATION1 )
					( AND
						( NOT ( BLOCKED ?LOCATION0 ?LOCATION1 ) )
						( NOT ( NEG-BLOCKED ?LOCATION0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?DOOR0 - DOOR ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
			( AND
				( WHEN
					( POS-HAS-DOOR ?DOOR0 ?LOCATION1 ?LOCATION2 )
					( AND
						( HAS-DOOR ?DOOR0 ?LOCATION1 ?LOCATION2 )
						( NOT ( POS-HAS-DOOR ?DOOR0 ?LOCATION1 ?LOCATION2 ) )
					)
				)
			)
		)
		( FORALL
			( ?DOOR0 - DOOR ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
			( AND
				( WHEN
					( NEG-HAS-DOOR ?DOOR0 ?LOCATION1 ?LOCATION2 )
					( AND
						( NOT ( HAS-DOOR ?DOOR0 ?LOCATION1 ?LOCATION2 ) )
						( NOT ( NEG-HAS-DOOR ?DOOR0 ?LOCATION1 ?LOCATION2 ) )
					)
				)
			)
		)
		( FORALL
			( ?BOAT0 - BOAT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
			( AND
				( WHEN
					( POS-HAS-BOAT ?BOAT0 ?LOCATION1 ?LOCATION2 )
					( AND
						( HAS-BOAT ?BOAT0 ?LOCATION1 ?LOCATION2 )
						( NOT ( POS-HAS-BOAT ?BOAT0 ?LOCATION1 ?LOCATION2 ) )
					)
				)
			)
		)
		( FORALL
			( ?BOAT0 - BOAT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
			( AND
				( WHEN
					( NEG-HAS-BOAT ?BOAT0 ?LOCATION1 ?LOCATION2 )
					( AND
						( NOT ( HAS-BOAT ?BOAT0 ?LOCATION1 ?LOCATION2 ) )
						( NOT ( NEG-HAS-BOAT ?BOAT0 ?LOCATION1 ?LOCATION2 ) )
					)
				)
			)
		)
		( FORALL
			( ?BOAT0 - BOAT ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-AT-BOAT ?BOAT0 ?LOCATION1 )
					( AND
						( AT-BOAT ?BOAT0 ?LOCATION1 )
						( NOT ( POS-AT-BOAT ?BOAT0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?BOAT0 - BOAT ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-AT-BOAT ?BOAT0 ?LOCATION1 )
					( AND
						( NOT ( AT-BOAT ?BOAT0 ?LOCATION1 ) )
						( NOT ( NEG-AT-BOAT ?BOAT0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?BRIDGE0 - BRIDGE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
			( AND
				( WHEN
					( POS-HAS-BRIDGE ?BRIDGE0 ?LOCATION1 ?LOCATION2 )
					( AND
						( HAS-BRIDGE ?BRIDGE0 ?LOCATION1 ?LOCATION2 )
						( NOT ( POS-HAS-BRIDGE ?BRIDGE0 ?LOCATION1 ?LOCATION2 ) )
					)
				)
			)
		)
		( FORALL
			( ?BRIDGE0 - BRIDGE ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
			( AND
				( WHEN
					( NEG-HAS-BRIDGE ?BRIDGE0 ?LOCATION1 ?LOCATION2 )
					( AND
						( NOT ( HAS-BRIDGE ?BRIDGE0 ?LOCATION1 ?LOCATION2 ) )
						( NOT ( NEG-HAS-BRIDGE ?BRIDGE0 ?LOCATION1 ?LOCATION2 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT )
			( AND
				( WHEN
					( POS-SAME-AGENT ?AGENT0 ?AGENT1 )
					( AND
						( SAME-AGENT ?AGENT0 ?AGENT1 )
						( NOT ( POS-SAME-AGENT ?AGENT0 ?AGENT1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT )
			( AND
				( WHEN
					( NEG-SAME-AGENT ?AGENT0 ?AGENT1 )
					( AND
						( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
						( NOT ( NEG-SAME-AGENT ?AGENT0 ?AGENT1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( NOT ( TAKEN ?AGENT0 ) )
		)
	)
)
)

;The domain compilation time is: 0.004842

