;;
;;	BOXPUSHING DOMAIN 
;;
( DEFINE ( DOMAIN BOXPUSHING )
( :REQUIREMENTS :TYPING )
( :TYPES
	OBJECT - OBJECT
	AGENT - OBJECT
	BOX - OBJECT
	LOCATION - OBJECT
)
( :PREDICATES
	( BOX-AT-LOC ?BOX0 - BOX ?LOCATION1 - LOCATION )
	( POS-BOX-AT-LOC ?BOX0 - BOX ?LOCATION1 - LOCATION )
	( NEG-BOX-AT-LOC ?BOX0 - BOX ?LOCATION1 - LOCATION )
	( AGENT-AT-LOC ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( POS-AGENT-AT-LOC ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( NEG-AGENT-AT-LOC ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( CONNECTED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( POS-CONNECTED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( NEG-CONNECTED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( TIRED ?AGENT0 - AGENT )
	( POS-TIRED ?AGENT0 - AGENT )
	( NEG-TIRED ?AGENT0 - AGENT )
	( SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( POS-SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( NEG-SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( TAKEN ?AGENT0 - AGENT )
	( NEG-IN-JOINT )
	( P-MOVE-AGENT ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( P-PUSH-BOX ?AGENT0 - AGENT ?BOX1 - BOX ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( P-JOINT-PUSH-BOX-PUSH-BOX ?AGENT0 - AGENT ?AGENT1 - AGENT ?BOX2 - BOX ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION )
)
( :ACTION MULTI-START
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( NEG-IN-JOINT )
	)
  :EFFECT
	( AND
		( NOT ( NEG-IN-JOINT ) )
	)
)
( :ACTION MOVE-AGENT
  :PARAMETERS ( ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION1 )
		( CONNECTED ?LOCATION1 ?LOCATION2 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( NEG-AGENT-AT-LOC ?AGENT0 ?LOCATION1 )
		( POS-AGENT-AT-LOC ?AGENT0 ?LOCATION2 )
		( TAKEN ?AGENT0 )
		( P-MOVE-AGENT ?AGENT0 ?LOCATION1 ?LOCATION2 )
	)
)
( :ACTION PUSH-BOX
  :PARAMETERS ( ?AGENT0 - AGENT ?BOX1 - BOX ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION2 )
		( BOX-AT-LOC ?BOX1 ?LOCATION2 )
		( CONNECTED ?LOCATION2 ?LOCATION3 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( POS-AGENT-AT-LOC ?AGENT0 ?LOCATION3 )
		( POS-BOX-AT-LOC ?BOX1 ?LOCATION3 )
		( NEG-AGENT-AT-LOC ?AGENT0 ?LOCATION2 )
		( NEG-BOX-AT-LOC ?BOX1 ?LOCATION2 )
		( POS-TIRED ?AGENT0 )
		( TAKEN ?AGENT0 )
		( P-PUSH-BOX ?AGENT0 ?BOX1 ?LOCATION2 ?LOCATION3 )
	)
)
( :ACTION JOINT-PUSH-BOX-PUSH-BOX
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?BOX2 - BOX ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION )
  :PRECONDITION
	( AND
		( AGENT-AT-LOC ?AGENT0 ?LOCATION3 )
		( AGENT-AT-LOC ?AGENT1 ?LOCATION3 )
		( BOX-AT-LOC ?BOX2 ?LOCATION3 )
		( CONNECTED ?LOCATION3 ?LOCATION4 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TIRED ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( POS-AGENT-AT-LOC ?AGENT0 ?LOCATION4 )
		( POS-AGENT-AT-LOC ?AGENT1 ?LOCATION4 )
		( POS-BOX-AT-LOC ?BOX2 ?LOCATION4 )
		( NEG-AGENT-AT-LOC ?AGENT0 ?LOCATION3 )
		( NEG-AGENT-AT-LOC ?AGENT1 ?LOCATION3 )
		( NEG-BOX-AT-LOC ?BOX2 ?LOCATION3 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( P-JOINT-PUSH-BOX-PUSH-BOX ?AGENT0 ?AGENT1 ?BOX2 ?LOCATION3 ?LOCATION4 )
		( P-PUSH-BOX ?AGENT0 ?BOX2 ?LOCATION3 ?LOCATION4 )
		( P-PUSH-BOX ?AGENT1 ?BOX2 ?LOCATION3 ?LOCATION4 )
	)
)
( :ACTION MULTI-END
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( NEG-IN-JOINT )
		( FORALL
			( ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
			( NOT ( P-MOVE-AGENT ?AGENT0 ?LOCATION1 ?LOCATION2 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?BOX1 - BOX ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
			( NOT ( P-PUSH-BOX ?AGENT0 ?BOX1 ?LOCATION2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?BOX2 - BOX ?LOCATION3 - LOCATION ?LOCATION4 - LOCATION )
			( NOT ( P-JOINT-PUSH-BOX-PUSH-BOX ?AGENT0 ?AGENT1 ?BOX2 ?LOCATION3 ?LOCATION4 ) )
		)
		( FORALL
			( ?BOX0 - BOX ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-BOX-AT-LOC ?BOX0 ?LOCATION1 )
					( AND
						( BOX-AT-LOC ?BOX0 ?LOCATION1 )
						( NOT ( POS-BOX-AT-LOC ?BOX0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?BOX0 - BOX ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-BOX-AT-LOC ?BOX0 ?LOCATION1 )
					( AND
						( NOT ( BOX-AT-LOC ?BOX0 ?LOCATION1 ) )
						( NOT ( NEG-BOX-AT-LOC ?BOX0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-AGENT-AT-LOC ?AGENT0 ?LOCATION1 )
					( AND
						( AGENT-AT-LOC ?AGENT0 ?LOCATION1 )
						( NOT ( POS-AGENT-AT-LOC ?AGENT0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-AGENT-AT-LOC ?AGENT0 ?LOCATION1 )
					( AND
						( NOT ( AGENT-AT-LOC ?AGENT0 ?LOCATION1 ) )
						( NOT ( NEG-AGENT-AT-LOC ?AGENT0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-CONNECTED ?LOCATION0 ?LOCATION1 )
					( AND
						( CONNECTED ?LOCATION0 ?LOCATION1 )
						( NOT ( POS-CONNECTED ?LOCATION0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-CONNECTED ?LOCATION0 ?LOCATION1 )
					( AND
						( NOT ( CONNECTED ?LOCATION0 ?LOCATION1 ) )
						( NOT ( NEG-CONNECTED ?LOCATION0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( AND
				( WHEN
					( POS-TIRED ?AGENT0 )
					( AND
						( TIRED ?AGENT0 )
						( NOT ( POS-TIRED ?AGENT0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( AND
				( WHEN
					( NEG-TIRED ?AGENT0 )
					( AND
						( NOT ( TIRED ?AGENT0 ) )
						( NOT ( NEG-TIRED ?AGENT0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT )
			( AND
				( WHEN
					( POS-SAME-AGENT ?AGENT0 ?AGENT1 )
					( AND
						( SAME-AGENT ?AGENT0 ?AGENT1 )
						( NOT ( POS-SAME-AGENT ?AGENT0 ?AGENT1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT )
			( AND
				( WHEN
					( NEG-SAME-AGENT ?AGENT0 ?AGENT1 )
					( AND
						( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
						( NOT ( NEG-SAME-AGENT ?AGENT0 ?AGENT1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( NOT ( TAKEN ?AGENT0 ) )
		)
	)
)
)

;;Domain compilation time is: 0.004766

