;;
;;	BOXPUSHING DOMAIN 
;;
( DEFINE ( DOMAIN BOXPUSHING )
( :REQUIREMENTS :TYPING )
( :TYPES
	AGENT - OBJECT
	BOX - OBJECT
	LOCATION - OBJECT
	AGENT-COUNT - OBJECT
)
( :CONSTANTS
	ACOUNT-0 - AGENT-COUNT
)
( :PREDICATES
	( BOX-AT-LOC ?BOX0 - BOX ?LOCATION1 - LOCATION )
	( AGENT-AT-LOC ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( CONNECTED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( TIRED ?AGENT0 - AGENT )
	( TAKEN ?AGENT0 - AGENT )
	( CONSEC ?AGENT-COUNT0 - AGENT-COUNT ?AGENT-COUNT1 - AGENT-COUNT )
	( AFREE )
	( IN-JOINT )
)
)


;Domain compilation time is: 0.000443

