;;
;;	APARTMENTMOVERS DOMAIN 
;;
( DEFINE ( DOMAIN APARTMENTMOVERS )
( :REQUIREMENTS :CONDITIONAL-EFFECTS :TYPING )
( :TYPES
	OBJECT - OBJECT
	AGENT - OBJECT
	FURNITURE - OBJECT
	ELECTRONICS - OBJECT
	CARTON - OBJECT
	TRUCK - OBJECT
	LOCATION - OBJECT
)
( :PREDICATES
	( AGENT-AT ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( POS-AGENT-AT ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( NEG-AGENT-AT ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
	( FURNITURE-AT ?FURNITURE0 - FURNITURE ?LOCATION1 - LOCATION )
	( POS-FURNITURE-AT ?FURNITURE0 - FURNITURE ?LOCATION1 - LOCATION )
	( NEG-FURNITURE-AT ?FURNITURE0 - FURNITURE ?LOCATION1 - LOCATION )
	( ELECTRONICS-AT ?ELECTRONICS0 - ELECTRONICS ?LOCATION1 - LOCATION )
	( POS-ELECTRONICS-AT ?ELECTRONICS0 - ELECTRONICS ?LOCATION1 - LOCATION )
	( NEG-ELECTRONICS-AT ?ELECTRONICS0 - ELECTRONICS ?LOCATION1 - LOCATION )
	( ELECTRONICS-IN ?ELECTRONICS0 - ELECTRONICS ?CARTON1 - CARTON )
	( POS-ELECTRONICS-IN ?ELECTRONICS0 - ELECTRONICS ?CARTON1 - CARTON )
	( NEG-ELECTRONICS-IN ?ELECTRONICS0 - ELECTRONICS ?CARTON1 - CARTON )
	( CARTON-AT ?CARTON0 - CARTON ?LOCATION1 - LOCATION )
	( POS-CARTON-AT ?CARTON0 - CARTON ?LOCATION1 - LOCATION )
	( NEG-CARTON-AT ?CARTON0 - CARTON ?LOCATION1 - LOCATION )
	( TRUCK-AT ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION )
	( POS-TRUCK-AT ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION )
	( NEG-TRUCK-AT ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION )
	( CONNECTED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( POS-CONNECTED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( NEG-CONNECTED ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
	( LOADED-FURNITURE ?FURNITURE0 - FURNITURE ?TRUCK1 - TRUCK )
	( POS-LOADED-FURNITURE ?FURNITURE0 - FURNITURE ?TRUCK1 - TRUCK )
	( NEG-LOADED-FURNITURE ?FURNITURE0 - FURNITURE ?TRUCK1 - TRUCK )
	( LOADED-CARTON ?CARTON0 - CARTON ?TRUCK1 - TRUCK )
	( POS-LOADED-CARTON ?CARTON0 - CARTON ?TRUCK1 - TRUCK )
	( NEG-LOADED-CARTON ?CARTON0 - CARTON ?TRUCK1 - TRUCK )
	( INSIDE ?ELECTRONICS0 - ELECTRONICS ?CARTON1 - CARTON )
	( POS-INSIDE ?ELECTRONICS0 - ELECTRONICS ?CARTON1 - CARTON )
	( NEG-INSIDE ?ELECTRONICS0 - ELECTRONICS ?CARTON1 - CARTON )
	( PACKED ?CARTON0 - CARTON )
	( POS-PACKED ?CARTON0 - CARTON )
	( NEG-PACKED ?CARTON0 - CARTON )
	( TIRED ?AGENT0 - AGENT )
	( POS-TIRED ?AGENT0 - AGENT )
	( NEG-TIRED ?AGENT0 - AGENT )
	( CAN-WALK ?AGENT0 - AGENT )
	( POS-CAN-WALK ?AGENT0 - AGENT )
	( NEG-CAN-WALK ?AGENT0 - AGENT )
	( SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( POS-SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( NEG-SAME-AGENT ?AGENT0 - AGENT ?AGENT1 - AGENT )
	( TAKEN ?AGENT0 - AGENT )
	( NEG-IN-JOINT )
	( P-CONSUME ?AGENT0 - AGENT )
	( P-MOVE-AGENT ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
	( P-LOAD-FURNITURE ?AGENT0 - AGENT ?FURNITURE1 - FURNITURE ?TRUCK2 - TRUCK ?LOCATION3 - LOCATION )
	( P-2-LOAD-FURNITURE ?AGENT0 - AGENT ?AGENT1 - AGENT ?FURNITURE2 - FURNITURE ?TRUCK3 - TRUCK ?LOCATION4 - LOCATION )
	( P-3-LOAD-FURNITURE ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?FURNITURE3 - FURNITURE ?TRUCK4 - TRUCK ?LOCATION5 - LOCATION )
	( P-UNLOAD-FURNITURE ?AGENT0 - AGENT ?FURNITURE1 - FURNITURE ?TRUCK2 - TRUCK ?LOCATION3 - LOCATION )
	( P-2-UNLOAD-FURNITURE ?AGENT0 - AGENT ?AGENT1 - AGENT ?FURNITURE2 - FURNITURE ?TRUCK3 - TRUCK ?LOCATION4 - LOCATION )
	( P-3-UNLOAD-FURNITURE ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?FURNITURE3 - FURNITURE ?TRUCK4 - TRUCK ?LOCATION5 - LOCATION )
	( P-DRIVE-TRUCK ?AGENT0 - AGENT ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
	( P-LOAD-CARTON ?AGENT0 - AGENT ?CARTON1 - CARTON ?TRUCK2 - TRUCK ?LOCATION3 - LOCATION )
	( P-2-LOAD-CARTON ?AGENT0 - AGENT ?AGENT1 - AGENT ?CARTON2 - CARTON ?TRUCK3 - TRUCK ?LOCATION4 - LOCATION )
	( P-UNLOAD-CARTON ?AGENT0 - AGENT ?CARTON1 - CARTON ?TRUCK2 - TRUCK ?LOCATION3 - LOCATION )
	( P-2-UNLOAD-CARTON ?AGENT0 - AGENT ?AGENT1 - AGENT ?CARTON2 - CARTON ?TRUCK3 - TRUCK ?LOCATION4 - LOCATION )
	( P-UNPACK-APPLIANCE ?AGENT0 - AGENT ?ELECTRONICS1 - ELECTRONICS ?CARTON2 - CARTON ?LOCATION3 - LOCATION )
	( P-PACK-APPLIANCE ?AGENT0 - AGENT ?ELECTRONICS1 - ELECTRONICS ?CARTON2 - CARTON ?LOCATION3 - LOCATION )
)
( :ACTION MULTI-START
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( NEG-IN-JOINT )
	)
  :EFFECT
	( AND
		( NOT ( NEG-IN-JOINT ) )
	)
)
( :ACTION CONSUME
  :PARAMETERS ( ?AGENT0 - AGENT )
  :PRECONDITION
	( AND
		( TIRED ?AGENT0 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( NEG-TIRED ?AGENT0 )
		( TAKEN ?AGENT0 )
		( P-CONSUME ?AGENT0 )
	)
)
( :ACTION MOVE-AGENT
  :PARAMETERS ( ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
  :PRECONDITION
	( AND
		( AGENT-AT ?AGENT0 ?LOCATION1 )
		( CONNECTED ?LOCATION1 ?LOCATION2 )
		( CAN-WALK ?AGENT0 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( POS-AGENT-AT ?AGENT0 ?LOCATION2 )
		( NEG-AGENT-AT ?AGENT0 ?LOCATION1 )
		( TAKEN ?AGENT0 )
		( P-MOVE-AGENT ?AGENT0 ?LOCATION1 ?LOCATION2 )
	)
)
( :ACTION LOAD-FURNITURE
  :PARAMETERS ( ?AGENT0 - AGENT ?FURNITURE1 - FURNITURE ?TRUCK2 - TRUCK ?LOCATION3 - LOCATION )
  :PRECONDITION
	( AND
		( AGENT-AT ?AGENT0 ?LOCATION3 )
		( FURNITURE-AT ?FURNITURE1 ?LOCATION3 )
		( TRUCK-AT ?TRUCK2 ?LOCATION3 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( P-LOAD-FURNITURE ?AGENT4 ?FURNITURE1 ?TRUCK2 ?LOCATION3 ) )
		)
	)
  :EFFECT
	( AND
		( POS-TIRED ?AGENT0 )
		( TAKEN ?AGENT0 )
		( P-LOAD-FURNITURE ?AGENT0 ?FURNITURE1 ?TRUCK2 ?LOCATION3 )
	)
)
( :ACTION 2-LOAD-FURNITURE
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?FURNITURE2 - FURNITURE ?TRUCK3 - TRUCK ?LOCATION4 - LOCATION )
  :PRECONDITION
	( AND
		( AGENT-AT ?AGENT0 ?LOCATION4 )
		( AGENT-AT ?AGENT1 ?LOCATION4 )
		( FURNITURE-AT ?FURNITURE2 ?LOCATION4 )
		( TRUCK-AT ?TRUCK3 ?LOCATION4 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TIRED ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT5 - AGENT )
			( NOT ( P-LOAD-FURNITURE ?AGENT5 ?FURNITURE2 ?TRUCK3 ?LOCATION4 ) )
		)
	)
  :EFFECT
	( AND
		( POS-LOADED-FURNITURE ?FURNITURE2 ?TRUCK3 )
		( NEG-FURNITURE-AT ?FURNITURE2 ?LOCATION4 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( P-2-LOAD-FURNITURE ?AGENT0 ?AGENT1 ?FURNITURE2 ?TRUCK3 ?LOCATION4 )
		( P-LOAD-FURNITURE ?AGENT0 ?FURNITURE2 ?TRUCK3 ?LOCATION4 )
		( P-LOAD-FURNITURE ?AGENT1 ?FURNITURE2 ?TRUCK3 ?LOCATION4 )
	)
)
( :ACTION 3-LOAD-FURNITURE
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?FURNITURE3 - FURNITURE ?TRUCK4 - TRUCK ?LOCATION5 - LOCATION )
  :PRECONDITION
	( AND
		( AGENT-AT ?AGENT0 ?LOCATION5 )
		( AGENT-AT ?AGENT1 ?LOCATION5 )
		( AGENT-AT ?AGENT2 ?LOCATION5 )
		( FURNITURE-AT ?FURNITURE3 ?LOCATION5 )
		( TRUCK-AT ?TRUCK4 ?LOCATION5 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TIRED ?AGENT1 ) )
		( NOT ( TIRED ?AGENT2 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT2 ) )
		( NOT ( SAME-AGENT ?AGENT1 ?AGENT2 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT2 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT6 - AGENT )
			( NOT ( P-LOAD-FURNITURE ?AGENT6 ?FURNITURE3 ?TRUCK4 ?LOCATION5 ) )
		)
	)
  :EFFECT
	( AND
		( POS-LOADED-FURNITURE ?FURNITURE3 ?TRUCK4 )
		( NEG-FURNITURE-AT ?FURNITURE3 ?LOCATION5 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( TAKEN ?AGENT2 )
		( P-3-LOAD-FURNITURE ?AGENT0 ?AGENT1 ?AGENT2 ?FURNITURE3 ?TRUCK4 ?LOCATION5 )
		( P-LOAD-FURNITURE ?AGENT0 ?FURNITURE3 ?TRUCK4 ?LOCATION5 )
		( P-LOAD-FURNITURE ?AGENT1 ?FURNITURE3 ?TRUCK4 ?LOCATION5 )
		( P-LOAD-FURNITURE ?AGENT2 ?FURNITURE3 ?TRUCK4 ?LOCATION5 )
	)
)
( :ACTION UNLOAD-FURNITURE
  :PARAMETERS ( ?AGENT0 - AGENT ?FURNITURE1 - FURNITURE ?TRUCK2 - TRUCK ?LOCATION3 - LOCATION )
  :PRECONDITION
	( AND
		( LOADED-FURNITURE ?FURNITURE1 ?TRUCK2 )
		( AGENT-AT ?AGENT0 ?LOCATION3 )
		( TRUCK-AT ?TRUCK2 ?LOCATION3 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( P-UNLOAD-FURNITURE ?AGENT4 ?FURNITURE1 ?TRUCK2 ?LOCATION3 ) )
		)
	)
  :EFFECT
	( AND
		( POS-TIRED ?AGENT0 )
		( TAKEN ?AGENT0 )
		( P-UNLOAD-FURNITURE ?AGENT0 ?FURNITURE1 ?TRUCK2 ?LOCATION3 )
		( P-LOAD-FURNITURE ?AGENT0 ?FURNITURE1 ?TRUCK2 ?LOCATION3 )
	)
)
( :ACTION 2-UNLOAD-FURNITURE
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?FURNITURE2 - FURNITURE ?TRUCK3 - TRUCK ?LOCATION4 - LOCATION )
  :PRECONDITION
	( AND
		( LOADED-FURNITURE ?FURNITURE2 ?TRUCK3 )
		( AGENT-AT ?AGENT0 ?LOCATION4 )
		( AGENT-AT ?AGENT1 ?LOCATION4 )
		( TRUCK-AT ?TRUCK3 ?LOCATION4 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TIRED ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT5 - AGENT )
			( NOT ( P-UNLOAD-FURNITURE ?AGENT5 ?FURNITURE2 ?TRUCK3 ?LOCATION4 ) )
		)
	)
  :EFFECT
	( AND
		( POS-FURNITURE-AT ?FURNITURE2 ?LOCATION4 )
		( NEG-LOADED-FURNITURE ?FURNITURE2 ?TRUCK3 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( P-2-UNLOAD-FURNITURE ?AGENT0 ?AGENT1 ?FURNITURE2 ?TRUCK3 ?LOCATION4 )
		( P-LOAD-FURNITURE ?AGENT0 ?FURNITURE2 ?TRUCK3 ?LOCATION4 )
		( P-LOAD-FURNITURE ?AGENT1 ?FURNITURE2 ?TRUCK3 ?LOCATION4 )
		( P-UNLOAD-FURNITURE ?AGENT0 ?FURNITURE2 ?TRUCK3 ?LOCATION4 )
		( P-UNLOAD-FURNITURE ?AGENT1 ?FURNITURE2 ?TRUCK3 ?LOCATION4 )
	)
)
( :ACTION 3-UNLOAD-FURNITURE
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?FURNITURE3 - FURNITURE ?TRUCK4 - TRUCK ?LOCATION5 - LOCATION )
  :PRECONDITION
	( AND
		( LOADED-FURNITURE ?FURNITURE3 ?TRUCK4 )
		( AGENT-AT ?AGENT0 ?LOCATION5 )
		( AGENT-AT ?AGENT1 ?LOCATION5 )
		( AGENT-AT ?AGENT2 ?LOCATION5 )
		( TRUCK-AT ?TRUCK4 ?LOCATION5 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TIRED ?AGENT1 ) )
		( NOT ( TIRED ?AGENT2 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT2 ) )
		( NOT ( SAME-AGENT ?AGENT1 ?AGENT2 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT2 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT6 - AGENT )
			( NOT ( P-UNLOAD-FURNITURE ?AGENT6 ?FURNITURE3 ?TRUCK4 ?LOCATION5 ) )
		)
	)
  :EFFECT
	( AND
		( POS-FURNITURE-AT ?FURNITURE3 ?LOCATION5 )
		( NEG-LOADED-FURNITURE ?FURNITURE3 ?TRUCK4 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( TAKEN ?AGENT2 )
		( P-3-UNLOAD-FURNITURE ?AGENT0 ?AGENT1 ?AGENT2 ?FURNITURE3 ?TRUCK4 ?LOCATION5 )
		( P-LOAD-FURNITURE ?AGENT0 ?FURNITURE3 ?TRUCK4 ?LOCATION5 )
		( P-LOAD-FURNITURE ?AGENT1 ?FURNITURE3 ?TRUCK4 ?LOCATION5 )
		( P-LOAD-FURNITURE ?AGENT2 ?FURNITURE3 ?TRUCK4 ?LOCATION5 )
		( P-UNLOAD-FURNITURE ?AGENT0 ?FURNITURE3 ?TRUCK4 ?LOCATION5 )
		( P-UNLOAD-FURNITURE ?AGENT1 ?FURNITURE3 ?TRUCK4 ?LOCATION5 )
		( P-UNLOAD-FURNITURE ?AGENT2 ?FURNITURE3 ?TRUCK4 ?LOCATION5 )
	)
)
( :ACTION DRIVE-TRUCK
  :PARAMETERS ( ?AGENT0 - AGENT ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
  :PRECONDITION
	( AND
		( NOT ( TIRED ?AGENT0 ) )
		( AGENT-AT ?AGENT0 ?LOCATION2 )
		( TRUCK-AT ?TRUCK1 ?LOCATION2 )
		( CONNECTED ?LOCATION2 ?LOCATION3 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( NEG-TRUCK-AT ?TRUCK1 ?LOCATION2 )
		( POS-TRUCK-AT ?TRUCK1 ?LOCATION3 )
		( NEG-AGENT-AT ?AGENT0 ?LOCATION2 )
		( POS-AGENT-AT ?AGENT0 ?LOCATION3 )
		( POS-TIRED ?AGENT0 )
		( TAKEN ?AGENT0 )
		( P-DRIVE-TRUCK ?AGENT0 ?TRUCK1 ?LOCATION2 ?LOCATION3 )
	)
)
( :ACTION LOAD-CARTON
  :PARAMETERS ( ?AGENT0 - AGENT ?CARTON1 - CARTON ?TRUCK2 - TRUCK ?LOCATION3 - LOCATION )
  :PRECONDITION
	( AND
		( CARTON-AT ?CARTON1 ?LOCATION3 )
		( PACKED ?CARTON1 )
		( AGENT-AT ?AGENT0 ?LOCATION3 )
		( TRUCK-AT ?TRUCK2 ?LOCATION3 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( P-LOAD-CARTON ?AGENT4 ?CARTON1 ?TRUCK2 ?LOCATION3 ) )
		)
	)
  :EFFECT
	( AND
		( POS-LOADED-CARTON ?CARTON1 ?TRUCK2 )
		( NEG-CARTON-AT ?CARTON1 ?LOCATION3 )
		( POS-TIRED ?AGENT0 )
		( TAKEN ?AGENT0 )
		( P-LOAD-CARTON ?AGENT0 ?CARTON1 ?TRUCK2 ?LOCATION3 )
	)
)
( :ACTION 2-LOAD-CARTON
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?CARTON2 - CARTON ?TRUCK3 - TRUCK ?LOCATION4 - LOCATION )
  :PRECONDITION
	( AND
		( CARTON-AT ?CARTON2 ?LOCATION4 )
		( PACKED ?CARTON2 )
		( AGENT-AT ?AGENT0 ?LOCATION4 )
		( AGENT-AT ?AGENT1 ?LOCATION4 )
		( TRUCK-AT ?TRUCK3 ?LOCATION4 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TIRED ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT5 - AGENT )
			( NOT ( P-LOAD-CARTON ?AGENT5 ?CARTON2 ?TRUCK3 ?LOCATION4 ) )
		)
	)
  :EFFECT
	( AND
		( POS-LOADED-CARTON ?CARTON2 ?TRUCK3 )
		( NEG-CARTON-AT ?CARTON2 ?LOCATION4 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( P-2-LOAD-CARTON ?AGENT0 ?AGENT1 ?CARTON2 ?TRUCK3 ?LOCATION4 )
		( P-LOAD-CARTON ?AGENT0 ?CARTON2 ?TRUCK3 ?LOCATION4 )
		( P-LOAD-CARTON ?AGENT1 ?CARTON2 ?TRUCK3 ?LOCATION4 )
	)
)
( :ACTION UNLOAD-CARTON
  :PARAMETERS ( ?AGENT0 - AGENT ?CARTON1 - CARTON ?TRUCK2 - TRUCK ?LOCATION3 - LOCATION )
  :PRECONDITION
	( AND
		( LOADED-CARTON ?CARTON1 ?TRUCK2 )
		( TRUCK-AT ?TRUCK2 ?LOCATION3 )
		( AGENT-AT ?AGENT0 ?LOCATION3 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT4 - AGENT )
			( NOT ( P-UNLOAD-CARTON ?AGENT4 ?CARTON1 ?TRUCK2 ?LOCATION3 ) )
		)
	)
  :EFFECT
	( AND
		( NEG-LOADED-CARTON ?CARTON1 ?TRUCK2 )
		( POS-CARTON-AT ?CARTON1 ?LOCATION3 )
		( POS-TIRED ?AGENT0 )
		( TAKEN ?AGENT0 )
		( P-UNLOAD-CARTON ?AGENT0 ?CARTON1 ?TRUCK2 ?LOCATION3 )
		( P-LOAD-CARTON ?AGENT0 ?CARTON1 ?TRUCK2 ?LOCATION3 )
	)
)
( :ACTION 2-UNLOAD-CARTON
  :PARAMETERS ( ?AGENT0 - AGENT ?AGENT1 - AGENT ?CARTON2 - CARTON ?TRUCK3 - TRUCK ?LOCATION4 - LOCATION )
  :PRECONDITION
	( AND
		( LOADED-CARTON ?CARTON2 ?TRUCK3 )
		( TRUCK-AT ?TRUCK3 ?LOCATION4 )
		( AGENT-AT ?AGENT0 ?LOCATION4 )
		( AGENT-AT ?AGENT1 ?LOCATION4 )
		( NOT ( TIRED ?AGENT0 ) )
		( NOT ( TIRED ?AGENT1 ) )
		( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( TAKEN ?AGENT1 ) )
		( NOT ( NEG-IN-JOINT ) )
		( FORALL
			( ?AGENT5 - AGENT )
			( NOT ( P-UNLOAD-CARTON ?AGENT5 ?CARTON2 ?TRUCK3 ?LOCATION4 ) )
		)
	)
  :EFFECT
	( AND
		( NEG-LOADED-CARTON ?CARTON2 ?TRUCK3 )
		( POS-CARTON-AT ?CARTON2 ?LOCATION4 )
		( TAKEN ?AGENT0 )
		( TAKEN ?AGENT1 )
		( P-2-UNLOAD-CARTON ?AGENT0 ?AGENT1 ?CARTON2 ?TRUCK3 ?LOCATION4 )
		( P-LOAD-CARTON ?AGENT0 ?CARTON2 ?TRUCK3 ?LOCATION4 )
		( P-LOAD-CARTON ?AGENT1 ?CARTON2 ?TRUCK3 ?LOCATION4 )
		( P-UNLOAD-CARTON ?AGENT0 ?CARTON2 ?TRUCK3 ?LOCATION4 )
		( P-UNLOAD-CARTON ?AGENT1 ?CARTON2 ?TRUCK3 ?LOCATION4 )
	)
)
( :ACTION UNPACK-APPLIANCE
  :PARAMETERS ( ?AGENT0 - AGENT ?ELECTRONICS1 - ELECTRONICS ?CARTON2 - CARTON ?LOCATION3 - LOCATION )
  :PRECONDITION
	( AND
		( PACKED ?CARTON2 )
		( CARTON-AT ?CARTON2 ?LOCATION3 )
		( ELECTRONICS-IN ?ELECTRONICS1 ?CARTON2 )
		( AGENT-AT ?AGENT0 ?LOCATION3 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( POS-ELECTRONICS-AT ?ELECTRONICS1 ?LOCATION3 )
		( NEG-ELECTRONICS-IN ?ELECTRONICS1 ?CARTON2 )
		( NEG-PACKED ?CARTON2 )
		( TAKEN ?AGENT0 )
		( P-UNPACK-APPLIANCE ?AGENT0 ?ELECTRONICS1 ?CARTON2 ?LOCATION3 )
	)
)
( :ACTION PACK-APPLIANCE
  :PARAMETERS ( ?AGENT0 - AGENT ?ELECTRONICS1 - ELECTRONICS ?CARTON2 - CARTON ?LOCATION3 - LOCATION )
  :PRECONDITION
	( AND
		( ELECTRONICS-AT ?ELECTRONICS1 ?LOCATION3 )
		( AGENT-AT ?AGENT0 ?LOCATION3 )
		( CARTON-AT ?CARTON2 ?LOCATION3 )
		( NOT ( TAKEN ?AGENT0 ) )
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( POS-ELECTRONICS-IN ?ELECTRONICS1 ?CARTON2 )
		( POS-PACKED ?CARTON2 )
		( NEG-ELECTRONICS-AT ?ELECTRONICS1 ?LOCATION3 )
		( TAKEN ?AGENT0 )
		( P-PACK-APPLIANCE ?AGENT0 ?ELECTRONICS1 ?CARTON2 ?LOCATION3 )
	)
)
( :ACTION MULTI-END
  :PARAMETERS ( )
  :PRECONDITION
	( AND
		( NOT ( NEG-IN-JOINT ) )
	)
  :EFFECT
	( AND
		( NEG-IN-JOINT )
		( FORALL
			( ?AGENT0 - AGENT )
			( NOT ( P-CONSUME ?AGENT0 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?LOCATION1 - LOCATION ?LOCATION2 - LOCATION )
			( NOT ( P-MOVE-AGENT ?AGENT0 ?LOCATION1 ?LOCATION2 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?FURNITURE1 - FURNITURE ?TRUCK2 - TRUCK ?LOCATION3 - LOCATION )
			( NOT ( P-LOAD-FURNITURE ?AGENT0 ?FURNITURE1 ?TRUCK2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?FURNITURE2 - FURNITURE ?TRUCK3 - TRUCK ?LOCATION4 - LOCATION )
			( NOT ( P-2-LOAD-FURNITURE ?AGENT0 ?AGENT1 ?FURNITURE2 ?TRUCK3 ?LOCATION4 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?FURNITURE3 - FURNITURE ?TRUCK4 - TRUCK ?LOCATION5 - LOCATION )
			( NOT ( P-3-LOAD-FURNITURE ?AGENT0 ?AGENT1 ?AGENT2 ?FURNITURE3 ?TRUCK4 ?LOCATION5 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?FURNITURE1 - FURNITURE ?TRUCK2 - TRUCK ?LOCATION3 - LOCATION )
			( NOT ( P-UNLOAD-FURNITURE ?AGENT0 ?FURNITURE1 ?TRUCK2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?FURNITURE2 - FURNITURE ?TRUCK3 - TRUCK ?LOCATION4 - LOCATION )
			( NOT ( P-2-UNLOAD-FURNITURE ?AGENT0 ?AGENT1 ?FURNITURE2 ?TRUCK3 ?LOCATION4 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?AGENT2 - AGENT ?FURNITURE3 - FURNITURE ?TRUCK4 - TRUCK ?LOCATION5 - LOCATION )
			( NOT ( P-3-UNLOAD-FURNITURE ?AGENT0 ?AGENT1 ?AGENT2 ?FURNITURE3 ?TRUCK4 ?LOCATION5 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?TRUCK1 - TRUCK ?LOCATION2 - LOCATION ?LOCATION3 - LOCATION )
			( NOT ( P-DRIVE-TRUCK ?AGENT0 ?TRUCK1 ?LOCATION2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?CARTON1 - CARTON ?TRUCK2 - TRUCK ?LOCATION3 - LOCATION )
			( NOT ( P-LOAD-CARTON ?AGENT0 ?CARTON1 ?TRUCK2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?CARTON2 - CARTON ?TRUCK3 - TRUCK ?LOCATION4 - LOCATION )
			( NOT ( P-2-LOAD-CARTON ?AGENT0 ?AGENT1 ?CARTON2 ?TRUCK3 ?LOCATION4 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?CARTON1 - CARTON ?TRUCK2 - TRUCK ?LOCATION3 - LOCATION )
			( NOT ( P-UNLOAD-CARTON ?AGENT0 ?CARTON1 ?TRUCK2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT ?CARTON2 - CARTON ?TRUCK3 - TRUCK ?LOCATION4 - LOCATION )
			( NOT ( P-2-UNLOAD-CARTON ?AGENT0 ?AGENT1 ?CARTON2 ?TRUCK3 ?LOCATION4 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?ELECTRONICS1 - ELECTRONICS ?CARTON2 - CARTON ?LOCATION3 - LOCATION )
			( NOT ( P-UNPACK-APPLIANCE ?AGENT0 ?ELECTRONICS1 ?CARTON2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?ELECTRONICS1 - ELECTRONICS ?CARTON2 - CARTON ?LOCATION3 - LOCATION )
			( NOT ( P-PACK-APPLIANCE ?AGENT0 ?ELECTRONICS1 ?CARTON2 ?LOCATION3 ) )
		)
		( FORALL
			( ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-AGENT-AT ?AGENT0 ?LOCATION1 )
					( AND
						( AGENT-AT ?AGENT0 ?LOCATION1 )
						( NOT ( POS-AGENT-AT ?AGENT0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-AGENT-AT ?AGENT0 ?LOCATION1 )
					( AND
						( NOT ( AGENT-AT ?AGENT0 ?LOCATION1 ) )
						( NOT ( NEG-AGENT-AT ?AGENT0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?FURNITURE0 - FURNITURE ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-FURNITURE-AT ?FURNITURE0 ?LOCATION1 )
					( AND
						( FURNITURE-AT ?FURNITURE0 ?LOCATION1 )
						( NOT ( POS-FURNITURE-AT ?FURNITURE0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?FURNITURE0 - FURNITURE ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-FURNITURE-AT ?FURNITURE0 ?LOCATION1 )
					( AND
						( NOT ( FURNITURE-AT ?FURNITURE0 ?LOCATION1 ) )
						( NOT ( NEG-FURNITURE-AT ?FURNITURE0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?ELECTRONICS0 - ELECTRONICS ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-ELECTRONICS-AT ?ELECTRONICS0 ?LOCATION1 )
					( AND
						( ELECTRONICS-AT ?ELECTRONICS0 ?LOCATION1 )
						( NOT ( POS-ELECTRONICS-AT ?ELECTRONICS0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?ELECTRONICS0 - ELECTRONICS ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-ELECTRONICS-AT ?ELECTRONICS0 ?LOCATION1 )
					( AND
						( NOT ( ELECTRONICS-AT ?ELECTRONICS0 ?LOCATION1 ) )
						( NOT ( NEG-ELECTRONICS-AT ?ELECTRONICS0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?ELECTRONICS0 - ELECTRONICS ?CARTON1 - CARTON )
			( AND
				( WHEN
					( POS-ELECTRONICS-IN ?ELECTRONICS0 ?CARTON1 )
					( AND
						( ELECTRONICS-IN ?ELECTRONICS0 ?CARTON1 )
						( NOT ( POS-ELECTRONICS-IN ?ELECTRONICS0 ?CARTON1 ) )
					)
				)
			)
		)
		( FORALL
			( ?ELECTRONICS0 - ELECTRONICS ?CARTON1 - CARTON )
			( AND
				( WHEN
					( NEG-ELECTRONICS-IN ?ELECTRONICS0 ?CARTON1 )
					( AND
						( NOT ( ELECTRONICS-IN ?ELECTRONICS0 ?CARTON1 ) )
						( NOT ( NEG-ELECTRONICS-IN ?ELECTRONICS0 ?CARTON1 ) )
					)
				)
			)
		)
		( FORALL
			( ?CARTON0 - CARTON ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-CARTON-AT ?CARTON0 ?LOCATION1 )
					( AND
						( CARTON-AT ?CARTON0 ?LOCATION1 )
						( NOT ( POS-CARTON-AT ?CARTON0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?CARTON0 - CARTON ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-CARTON-AT ?CARTON0 ?LOCATION1 )
					( AND
						( NOT ( CARTON-AT ?CARTON0 ?LOCATION1 ) )
						( NOT ( NEG-CARTON-AT ?CARTON0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-TRUCK-AT ?TRUCK0 ?LOCATION1 )
					( AND
						( TRUCK-AT ?TRUCK0 ?LOCATION1 )
						( NOT ( POS-TRUCK-AT ?TRUCK0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?TRUCK0 - TRUCK ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-TRUCK-AT ?TRUCK0 ?LOCATION1 )
					( AND
						( NOT ( TRUCK-AT ?TRUCK0 ?LOCATION1 ) )
						( NOT ( NEG-TRUCK-AT ?TRUCK0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( POS-CONNECTED ?LOCATION0 ?LOCATION1 )
					( AND
						( CONNECTED ?LOCATION0 ?LOCATION1 )
						( NOT ( POS-CONNECTED ?LOCATION0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?LOCATION0 - LOCATION ?LOCATION1 - LOCATION )
			( AND
				( WHEN
					( NEG-CONNECTED ?LOCATION0 ?LOCATION1 )
					( AND
						( NOT ( CONNECTED ?LOCATION0 ?LOCATION1 ) )
						( NOT ( NEG-CONNECTED ?LOCATION0 ?LOCATION1 ) )
					)
				)
			)
		)
		( FORALL
			( ?FURNITURE0 - FURNITURE ?TRUCK1 - TRUCK )
			( AND
				( WHEN
					( POS-LOADED-FURNITURE ?FURNITURE0 ?TRUCK1 )
					( AND
						( LOADED-FURNITURE ?FURNITURE0 ?TRUCK1 )
						( NOT ( POS-LOADED-FURNITURE ?FURNITURE0 ?TRUCK1 ) )
					)
				)
			)
		)
		( FORALL
			( ?FURNITURE0 - FURNITURE ?TRUCK1 - TRUCK )
			( AND
				( WHEN
					( NEG-LOADED-FURNITURE ?FURNITURE0 ?TRUCK1 )
					( AND
						( NOT ( LOADED-FURNITURE ?FURNITURE0 ?TRUCK1 ) )
						( NOT ( NEG-LOADED-FURNITURE ?FURNITURE0 ?TRUCK1 ) )
					)
				)
			)
		)
		( FORALL
			( ?CARTON0 - CARTON ?TRUCK1 - TRUCK )
			( AND
				( WHEN
					( POS-LOADED-CARTON ?CARTON0 ?TRUCK1 )
					( AND
						( LOADED-CARTON ?CARTON0 ?TRUCK1 )
						( NOT ( POS-LOADED-CARTON ?CARTON0 ?TRUCK1 ) )
					)
				)
			)
		)
		( FORALL
			( ?CARTON0 - CARTON ?TRUCK1 - TRUCK )
			( AND
				( WHEN
					( NEG-LOADED-CARTON ?CARTON0 ?TRUCK1 )
					( AND
						( NOT ( LOADED-CARTON ?CARTON0 ?TRUCK1 ) )
						( NOT ( NEG-LOADED-CARTON ?CARTON0 ?TRUCK1 ) )
					)
				)
			)
		)
		( FORALL
			( ?ELECTRONICS0 - ELECTRONICS ?CARTON1 - CARTON )
			( AND
				( WHEN
					( POS-INSIDE ?ELECTRONICS0 ?CARTON1 )
					( AND
						( INSIDE ?ELECTRONICS0 ?CARTON1 )
						( NOT ( POS-INSIDE ?ELECTRONICS0 ?CARTON1 ) )
					)
				)
			)
		)
		( FORALL
			( ?ELECTRONICS0 - ELECTRONICS ?CARTON1 - CARTON )
			( AND
				( WHEN
					( NEG-INSIDE ?ELECTRONICS0 ?CARTON1 )
					( AND
						( NOT ( INSIDE ?ELECTRONICS0 ?CARTON1 ) )
						( NOT ( NEG-INSIDE ?ELECTRONICS0 ?CARTON1 ) )
					)
				)
			)
		)
		( FORALL
			( ?CARTON0 - CARTON )
			( AND
				( WHEN
					( POS-PACKED ?CARTON0 )
					( AND
						( PACKED ?CARTON0 )
						( NOT ( POS-PACKED ?CARTON0 ) )
					)
				)
			)
		)
		( FORALL
			( ?CARTON0 - CARTON )
			( AND
				( WHEN
					( NEG-PACKED ?CARTON0 )
					( AND
						( NOT ( PACKED ?CARTON0 ) )
						( NOT ( NEG-PACKED ?CARTON0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( AND
				( WHEN
					( POS-TIRED ?AGENT0 )
					( AND
						( TIRED ?AGENT0 )
						( NOT ( POS-TIRED ?AGENT0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( AND
				( WHEN
					( NEG-TIRED ?AGENT0 )
					( AND
						( NOT ( TIRED ?AGENT0 ) )
						( NOT ( NEG-TIRED ?AGENT0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( AND
				( WHEN
					( POS-CAN-WALK ?AGENT0 )
					( AND
						( CAN-WALK ?AGENT0 )
						( NOT ( POS-CAN-WALK ?AGENT0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( AND
				( WHEN
					( NEG-CAN-WALK ?AGENT0 )
					( AND
						( NOT ( CAN-WALK ?AGENT0 ) )
						( NOT ( NEG-CAN-WALK ?AGENT0 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT )
			( AND
				( WHEN
					( POS-SAME-AGENT ?AGENT0 ?AGENT1 )
					( AND
						( SAME-AGENT ?AGENT0 ?AGENT1 )
						( NOT ( POS-SAME-AGENT ?AGENT0 ?AGENT1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT ?AGENT1 - AGENT )
			( AND
				( WHEN
					( NEG-SAME-AGENT ?AGENT0 ?AGENT1 )
					( AND
						( NOT ( SAME-AGENT ?AGENT0 ?AGENT1 ) )
						( NOT ( NEG-SAME-AGENT ?AGENT0 ?AGENT1 ) )
					)
				)
			)
		)
		( FORALL
			( ?AGENT0 - AGENT )
			( NOT ( TAKEN ?AGENT0 ) )
		)
	)
)
)

;The domain compilation time is: 0.016093

